/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.gespet.view;

import javax.swing.JOptionPane;
import br.inatel.gespet.model.Proprietario;

/**
 *
 * @author Brendhon
 */
public class TelaProprietario extends javax.swing.JFrame {

    /**
     * Creates new form TelaProprietario
     */
    public TelaProprietario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BordaLeft = new javax.swing.JPanel();
        IconVet = new javax.swing.JLabel();
        Vet = new javax.swing.JPanel();
        NomeVet = new javax.swing.JLabel();
        ButCliente = new javax.swing.JButton();
        ButAnimais = new javax.swing.JButton();
        ButVeterinario = new javax.swing.JButton();
        Bordinha = new javax.swing.JPanel();
        Bordinha1 = new javax.swing.JPanel();
        Bordinha2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BordaTop = new javax.swing.JPanel();
        IconeEditar = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        IconeCadastrar = new javax.swing.JLabel();
        TextNome = new javax.swing.JTextField();
        JIdade = new javax.swing.JLabel();
        TextCpf = new javax.swing.JTextField();
        Fundinho = new javax.swing.JLabel();
        JNome = new javax.swing.JLabel();
        Fundinho1 = new javax.swing.JLabel();
        JEspecie = new javax.swing.JLabel();
        TextAnimais = new javax.swing.JLabel();
        TextCelular = new javax.swing.JTextField();
        Fundinho2 = new javax.swing.JLabel();
        TextRua = new javax.swing.JTextField();
        JEspecie1 = new javax.swing.JLabel();
        Fundinho4 = new javax.swing.JLabel();
        BotCadastrarProprietario = new javax.swing.JLabel();
        TextBairro = new javax.swing.JTextField();
        Fundinho5 = new javax.swing.JLabel();
        JEspecie2 = new javax.swing.JLabel();
        TelaGeral = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BordaLeft.setBackground(new java.awt.Color(23, 105, 99));
        BordaLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconVet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconVet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Animal.png"))); // NOI18N
        BordaLeft.add(IconVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 130));

        Vet.setBackground(new java.awt.Color(1, 81, 74));

        NomeVet.setBackground(new java.awt.Color(255, 0, 153));
        NomeVet.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        NomeVet.setForeground(new java.awt.Color(255, 255, 255));
        NomeVet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomeVet.setText("NOME VET");
        NomeVet.setAlignmentX(0.5F);

        javax.swing.GroupLayout VetLayout = new javax.swing.GroupLayout(Vet);
        Vet.setLayout(VetLayout);
        VetLayout.setHorizontalGroup(
            VetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
            .addGroup(VetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(NomeVet, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
        );
        VetLayout.setVerticalGroup(
            VetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(VetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(NomeVet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
        );

        BordaLeft.add(Vet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 160, 60));

        ButCliente.setBackground(new java.awt.Color(71, 192, 161));
        ButCliente.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        ButCliente.setForeground(new java.awt.Color(255, 255, 255));
        ButCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Cliente.png"))); // NOI18N
        ButCliente.setText("CLIENTES");
        ButCliente.setBorder(null);
        ButCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButClienteActionPerformed(evt);
            }
        });
        BordaLeft.add(ButCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 150, 100));

        ButAnimais.setBackground(new java.awt.Color(71, 192, 161));
        ButAnimais.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        ButAnimais.setForeground(new java.awt.Color(255, 255, 255));
        ButAnimais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Animal.png"))); // NOI18N
        ButAnimais.setText("ANIMAIS");
        ButAnimais.setBorder(null);
        ButAnimais.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButAnimais.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButAnimais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAnimaisActionPerformed(evt);
            }
        });
        BordaLeft.add(ButAnimais, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 150, 100));

        ButVeterinario.setBackground(new java.awt.Color(71, 192, 161));
        ButVeterinario.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        ButVeterinario.setForeground(new java.awt.Color(255, 255, 255));
        ButVeterinario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Sair.png"))); // NOI18N
        ButVeterinario.setText("DESLOGAR");
        ButVeterinario.setBorder(null);
        ButVeterinario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButVeterinario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButVeterinarioActionPerformed(evt);
            }
        });
        BordaLeft.add(ButVeterinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 150, 100));

        Bordinha.setBackground(new java.awt.Color(1, 81, 74));

        javax.swing.GroupLayout BordinhaLayout = new javax.swing.GroupLayout(Bordinha);
        Bordinha.setLayout(BordinhaLayout);
        BordinhaLayout.setHorizontalGroup(
            BordinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        BordinhaLayout.setVerticalGroup(
            BordinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        BordaLeft.add(Bordinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 10, -1));

        Bordinha1.setBackground(new java.awt.Color(1, 81, 74));

        javax.swing.GroupLayout Bordinha1Layout = new javax.swing.GroupLayout(Bordinha1);
        Bordinha1.setLayout(Bordinha1Layout);
        Bordinha1Layout.setHorizontalGroup(
            Bordinha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Bordinha1Layout.setVerticalGroup(
            Bordinha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        BordaLeft.add(Bordinha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        Bordinha2.setBackground(new java.awt.Color(1, 81, 74));

        javax.swing.GroupLayout Bordinha2Layout = new javax.swing.GroupLayout(Bordinha2);
        Bordinha2.setLayout(Bordinha2Layout);
        Bordinha2Layout.setHorizontalGroup(
            Bordinha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Bordinha2Layout.setVerticalGroup(
            Bordinha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        BordaLeft.add(Bordinha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Configuracoes.png"))); // NOI18N
        BordaLeft.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 80, 80));

        getContentPane().add(BordaLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 720));

        BordaTop.setBackground(new java.awt.Color(1, 81, 74));
        BordaTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconeEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/IconEditar.png"))); // NOI18N
        IconeEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconeEditarMouseClicked(evt);
            }
        });
        BordaTop.add(IconeEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, 60));

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Home.png"))); // NOI18N
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        BordaTop.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, -1, -1, 90));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/OFF.png"))); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        BordaTop.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, -2, 60, 90));

        IconeCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/IconCadastrar.png"))); // NOI18N
        IconeCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconeCadastrarMouseClicked(evt);
            }
        });
        BordaTop.add(IconeCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 50, 60));

        getContentPane().add(BordaTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 990, 90));

        TextNome.setBackground(new java.awt.Color(232, 235, 244));
        TextNome.setFont(new java.awt.Font("Typo Hoop Demo", 0, 24)); // NOI18N
        TextNome.setBorder(null);
        getContentPane().add(TextNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 190, 30));

        JIdade.setFont(new java.awt.Font("Typo Hoop Demo", 1, 24)); // NOI18N
        JIdade.setForeground(new java.awt.Color(255, 255, 255));
        JIdade.setText("CPF");
        getContentPane().add(JIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 80, 30));

        TextCpf.setBackground(new java.awt.Color(232, 235, 244));
        TextCpf.setFont(new java.awt.Font("Typo Hoop Demo", 0, 24)); // NOI18N
        TextCpf.setBorder(null);
        getContentPane().add(TextCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, 190, 30));

        Fundinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Botao.png"))); // NOI18N
        getContentPane().add(Fundinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 240, 50));

        JNome.setFont(new java.awt.Font("Typo Hoop Demo", 1, 24)); // NOI18N
        JNome.setForeground(new java.awt.Color(255, 255, 255));
        JNome.setText("NOME");
        getContentPane().add(JNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 80, 30));

        Fundinho1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Botao.png"))); // NOI18N
        getContentPane().add(Fundinho1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 270, 240, 50));

        JEspecie.setFont(new java.awt.Font("Typo Hoop Demo", 1, 24)); // NOI18N
        JEspecie.setForeground(new java.awt.Color(255, 255, 255));
        JEspecie.setText("CELULAR");
        getContentPane().add(JEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 130, 30));

        TextAnimais.setBackground(new java.awt.Color(232, 235, 244));
        TextAnimais.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        TextAnimais.setForeground(new java.awt.Color(1, 81, 74));
        TextAnimais.setText("PROPRIETÁRIO");
        TextAnimais.setOpaque(true);
        getContentPane().add(TextAnimais, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        TextCelular.setBackground(new java.awt.Color(232, 235, 244));
        TextCelular.setFont(new java.awt.Font("Typo Hoop Demo", 0, 24)); // NOI18N
        TextCelular.setBorder(null);
        getContentPane().add(TextCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 190, 30));

        Fundinho2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Botao.png"))); // NOI18N
        getContentPane().add(Fundinho2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 240, 50));

        TextRua.setBackground(new java.awt.Color(232, 235, 244));
        TextRua.setFont(new java.awt.Font("Typo Hoop Demo", 0, 24)); // NOI18N
        TextRua.setBorder(null);
        getContentPane().add(TextRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 490, 30));

        JEspecie1.setFont(new java.awt.Font("Typo Hoop Demo", 1, 24)); // NOI18N
        JEspecie1.setForeground(new java.awt.Color(255, 255, 255));
        JEspecie1.setText("RUA");
        getContentPane().add(JEspecie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 70, 30));

        Fundinho4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Botao3_2.png"))); // NOI18N
        getContentPane().add(Fundinho4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 550, 50));

        BotCadastrarProprietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/BotCadastrar.png"))); // NOI18N
        BotCadastrarProprietario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotCadastrarProprietarioMouseClicked(evt);
            }
        });
        getContentPane().add(BotCadastrarProprietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 580, 170, 70));

        TextBairro.setBackground(new java.awt.Color(232, 235, 244));
        TextBairro.setFont(new java.awt.Font("Typo Hoop Demo", 0, 24)); // NOI18N
        TextBairro.setBorder(null);
        getContentPane().add(TextBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, 490, 30));

        Fundinho5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Botao3_2.png"))); // NOI18N
        getContentPane().add(Fundinho5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 550, 50));

        JEspecie2.setFont(new java.awt.Font("Typo Hoop Demo", 1, 24)); // NOI18N
        JEspecie2.setForeground(new java.awt.Color(255, 255, 255));
        JEspecie2.setText("Bairro");
        getContentPane().add(JEspecie2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 70, 30));

        TelaGeral.setBackground(new java.awt.Color(232, 235, 244));
        TelaGeral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Cadastrar.png"))); // NOI18N
        TelaGeral.setOpaque(true);
        getContentPane().add(TelaGeral, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        BG.setBackground(new java.awt.Color(232, 235, 244));
        BG.setOpaque(true);
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 920, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButClienteActionPerformed

        //Declaração de Objetos
        TelaProprietario screenPrt = new TelaProprietario();

        //Mostrando tela do Proprietario
        screenPrt.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_ButClienteActionPerformed

    private void ButAnimaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAnimaisActionPerformed

        //Declaração de Objetos
        TelaAnimais animaisScreen = new TelaAnimais();

        //Mostrar tela do Animal
        animaisScreen.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_ButAnimaisActionPerformed

    private void ButVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButVeterinarioActionPerformed
        //Declaração de Objetos
        TelaLogin t = new TelaLogin();

        //Mostrar tela de vacina
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButVeterinarioActionPerformed

    private void IconeEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconeEditarMouseClicked
        //Declaração de Objetos
        TelaEditarCliente t = new TelaEditarCliente();

        //Mostrar tela editar
        t.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_IconeEditarMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked

        //Declaração de Objetos
        TelaPrincipal t = new TelaPrincipal();

        //Mostrar tela Principal
        t.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_HomeMouseClicked

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked

        //Fechar programa
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void IconeCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconeCadastrarMouseClicked

        //Declaração de Objetos
        TelaAnimais animaisScreen = new TelaAnimais();

        //Mostrar tela Animal
        animaisScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IconeCadastrarMouseClicked

    private void BotCadastrarProprietarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotCadastrarProprietarioMouseClicked

        //Cadastrar
        cadastrarProprietario();

    }//GEN-LAST:event_BotCadastrarProprietarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProprietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProprietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProprietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProprietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProprietario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JPanel BordaLeft;
    private javax.swing.JPanel BordaTop;
    private javax.swing.JPanel Bordinha;
    private javax.swing.JPanel Bordinha1;
    private javax.swing.JPanel Bordinha2;
    private javax.swing.JLabel BotCadastrarProprietario;
    private javax.swing.JButton ButAnimais;
    private javax.swing.JButton ButCliente;
    private javax.swing.JButton ButVeterinario;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel Fundinho;
    private javax.swing.JLabel Fundinho1;
    private javax.swing.JLabel Fundinho2;
    private javax.swing.JLabel Fundinho4;
    private javax.swing.JLabel Fundinho5;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel IconVet;
    private javax.swing.JLabel IconeCadastrar;
    private javax.swing.JLabel IconeEditar;
    private javax.swing.JLabel JEspecie;
    private javax.swing.JLabel JEspecie1;
    private javax.swing.JLabel JEspecie2;
    private javax.swing.JLabel JIdade;
    private javax.swing.JLabel JNome;
    private javax.swing.JLabel NomeVet;
    private javax.swing.JLabel TelaGeral;
    private javax.swing.JLabel TextAnimais;
    private javax.swing.JTextField TextBairro;
    private javax.swing.JTextField TextCelular;
    private javax.swing.JTextField TextCpf;
    private javax.swing.JTextField TextNome;
    private javax.swing.JTextField TextRua;
    private javax.swing.JPanel Vet;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void cadastrarProprietario() {

        //Declaração de Objetos
        Proprietario propietario = new Proprietario();

        //Declaração de Variaveis
        boolean resultado;

        //Atribuição de valores
        if (TextCpf.getText().length() == 11) {

            propietario.setNome(TextNome.getText());
            propietario.setCpf(TextCpf.getText());
            propietario.setCelular(Integer.parseInt(TextCelular.getText()));
            propietario.setRua(TextRua.getText());
            propietario.setBairro(TextBairro.getText());

            //Inserindo no Banco
            resultado = propietario.Pdao.insert(propietario);

            //IFs de variaveis booleanas para conferir o sucesso
            if (resultado) {

                JOptionPane.showMessageDialog(null, "Sucesso ao Inserir!");
                TextNome.setText(null);
                TextCpf.setText(null);
                TextCelular.setText(null);
                TextRua.setText(null);
                TextBairro.setText(null);

            }
        } else {
            JOptionPane.showMessageDialog(null, "CPF DEVE POSSUIR 11 DIGITOS");
        }

    }

}
