/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.gespet.view;

import javax.swing.JOptionPane;
import br.inatel.gespet.model.Animal;

/**
 *
 * @author Brendhon
 */
public class TelaEditarAnimal extends javax.swing.JFrame {

    /**
     * Creates new form TelaEditarAnimal
     */
    public TelaEditarAnimal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BordaLeft = new javax.swing.JPanel();
        IconVet = new javax.swing.JLabel();
        Vet = new javax.swing.JPanel();
        NomeVet = new javax.swing.JLabel();
        ButCliente = new javax.swing.JButton();
        ButAnimais = new javax.swing.JButton();
        ButVeterinario = new javax.swing.JButton();
        Bordinha = new javax.swing.JPanel();
        Bordinha1 = new javax.swing.JPanel();
        Bordinha2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BordaTop = new javax.swing.JPanel();
        IconeEditar = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        IconeExcluir = new javax.swing.JLabel();
        IconeBuscar = new javax.swing.JLabel();
        IconeCadastrar = new javax.swing.JLabel();
        IconeVacinas = new javax.swing.JLabel();
        JNome1 = new javax.swing.JLabel();
        TextNome1 = new javax.swing.JTextField();
        Fundinho1 = new javax.swing.JLabel();
        JNome = new javax.swing.JLabel();
        TextNome = new javax.swing.JTextField();
        Fundinho = new javax.swing.JLabel();
        JNome2 = new javax.swing.JLabel();
        TextNomePet = new javax.swing.JTextField();
        Fundinho2 = new javax.swing.JLabel();
        JNome3 = new javax.swing.JLabel();
        TextRaca = new javax.swing.JTextField();
        Fundinho3 = new javax.swing.JLabel();
        JNome4 = new javax.swing.JLabel();
        TextIdadePet = new javax.swing.JTextField();
        JNome5 = new javax.swing.JLabel();
        Fundinho4 = new javax.swing.JLabel();
        TextSexo = new javax.swing.JTextField();
        Fundinho5 = new javax.swing.JLabel();
        TextEspecie = new javax.swing.JTextField();
        Fundinho6 = new javax.swing.JLabel();
        JNome6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BotConferir = new javax.swing.JLabel();
        TelaGeral = new javax.swing.JLabel();
        TextAnimais = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BordaLeft.setBackground(new java.awt.Color(23, 105, 99));
        BordaLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconVet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconVet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Animal.png"))); // NOI18N
        BordaLeft.add(IconVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 130));

        Vet.setBackground(new java.awt.Color(1, 81, 74));

        NomeVet.setBackground(new java.awt.Color(255, 0, 153));
        NomeVet.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        NomeVet.setForeground(new java.awt.Color(255, 255, 255));
        NomeVet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomeVet.setText("NOME VET");
        NomeVet.setAlignmentX(0.5F);

        javax.swing.GroupLayout VetLayout = new javax.swing.GroupLayout(Vet);
        Vet.setLayout(VetLayout);
        VetLayout.setHorizontalGroup(
            VetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
            .addGroup(VetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(NomeVet, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
        );
        VetLayout.setVerticalGroup(
            VetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(VetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(NomeVet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
        );

        BordaLeft.add(Vet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 160, 60));

        ButCliente.setBackground(new java.awt.Color(71, 192, 161));
        ButCliente.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        ButCliente.setForeground(new java.awt.Color(255, 255, 255));
        ButCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Cliente.png"))); // NOI18N
        ButCliente.setText("CLIENTES");
        ButCliente.setBorder(null);
        ButCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButClienteActionPerformed(evt);
            }
        });
        BordaLeft.add(ButCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 150, 100));

        ButAnimais.setBackground(new java.awt.Color(71, 192, 161));
        ButAnimais.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        ButAnimais.setForeground(new java.awt.Color(255, 255, 255));
        ButAnimais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Animal.png"))); // NOI18N
        ButAnimais.setText("ANIMAIS");
        ButAnimais.setBorder(null);
        ButAnimais.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButAnimais.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButAnimais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButAnimaisMouseClicked(evt);
            }
        });
        ButAnimais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAnimaisActionPerformed(evt);
            }
        });
        BordaLeft.add(ButAnimais, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 150, 100));

        ButVeterinario.setBackground(new java.awt.Color(71, 192, 161));
        ButVeterinario.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        ButVeterinario.setForeground(new java.awt.Color(255, 255, 255));
        ButVeterinario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Sair.png"))); // NOI18N
        ButVeterinario.setText("DESLOGAR");
        ButVeterinario.setBorder(null);
        ButVeterinario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButVeterinario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButVeterinarioActionPerformed(evt);
            }
        });
        BordaLeft.add(ButVeterinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 150, 100));

        Bordinha.setBackground(new java.awt.Color(1, 81, 74));

        javax.swing.GroupLayout BordinhaLayout = new javax.swing.GroupLayout(Bordinha);
        Bordinha.setLayout(BordinhaLayout);
        BordinhaLayout.setHorizontalGroup(
            BordinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        BordinhaLayout.setVerticalGroup(
            BordinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        BordaLeft.add(Bordinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 10, -1));

        Bordinha1.setBackground(new java.awt.Color(1, 81, 74));

        javax.swing.GroupLayout Bordinha1Layout = new javax.swing.GroupLayout(Bordinha1);
        Bordinha1.setLayout(Bordinha1Layout);
        Bordinha1Layout.setHorizontalGroup(
            Bordinha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Bordinha1Layout.setVerticalGroup(
            Bordinha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        BordaLeft.add(Bordinha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        Bordinha2.setBackground(new java.awt.Color(1, 81, 74));

        javax.swing.GroupLayout Bordinha2Layout = new javax.swing.GroupLayout(Bordinha2);
        Bordinha2.setLayout(Bordinha2Layout);
        Bordinha2Layout.setHorizontalGroup(
            Bordinha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Bordinha2Layout.setVerticalGroup(
            Bordinha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        BordaLeft.add(Bordinha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Configuracoes.png"))); // NOI18N
        BordaLeft.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 80, 80));

        getContentPane().add(BordaLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 720));

        BordaTop.setBackground(new java.awt.Color(1, 81, 74));
        BordaTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconeEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/IconEditar.png"))); // NOI18N
        IconeEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconeEditarMouseClicked(evt);
            }
        });
        BordaTop.add(IconeEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, 60));

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Home.png"))); // NOI18N
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        BordaTop.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, -1, -1, 90));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/OFF.png"))); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        BordaTop.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, -2, 60, 90));

        IconeExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/IconDeletar.png"))); // NOI18N
        IconeExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconeExcluirMouseClicked(evt);
            }
        });
        BordaTop.add(IconeExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 40, 60));

        IconeBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/IconPesquisar.png"))); // NOI18N
        IconeBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconeBuscarMouseClicked(evt);
            }
        });
        BordaTop.add(IconeBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 50, 60));

        IconeCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/IconCadastrar.png"))); // NOI18N
        IconeCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconeCadastrarMouseClicked(evt);
            }
        });
        BordaTop.add(IconeCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 50, 60));

        IconeVacinas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/IconVacina.png"))); // NOI18N
        IconeVacinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconeVacinasMouseClicked(evt);
            }
        });
        BordaTop.add(IconeVacinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, 80));

        getContentPane().add(BordaTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 990, 90));

        JNome1.setFont(new java.awt.Font("Typo Hoop Demo", 1, 24)); // NOI18N
        JNome1.setForeground(new java.awt.Color(255, 255, 255));
        JNome1.setText("NOME PROPRIETÁRIO");
        getContentPane().add(JNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 280, 30));

        TextNome1.setBackground(new java.awt.Color(232, 235, 244));
        TextNome1.setFont(new java.awt.Font("Typo Hoop Demo", 0, 24)); // NOI18N
        TextNome1.setBorder(null);
        getContentPane().add(TextNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 270, 30));

        Fundinho1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Botao4.png"))); // NOI18N
        getContentPane().add(Fundinho1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 320, 50));

        JNome.setFont(new java.awt.Font("Typo Hoop Demo", 1, 24)); // NOI18N
        JNome.setForeground(new java.awt.Color(255, 255, 255));
        JNome.setText("NOME");
        getContentPane().add(JNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 80, 30));

        TextNome.setBackground(new java.awt.Color(232, 235, 244));
        TextNome.setFont(new java.awt.Font("Typo Hoop Demo", 0, 24)); // NOI18N
        TextNome.setBorder(null);
        getContentPane().add(TextNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 190, 30));

        Fundinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Botao.png"))); // NOI18N
        getContentPane().add(Fundinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 240, 50));

        JNome2.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        JNome2.setForeground(new java.awt.Color(255, 255, 255));
        JNome2.setText("NOME");
        getContentPane().add(JNome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 60, 20));

        TextNomePet.setEditable(false);
        TextNomePet.setBackground(new java.awt.Color(232, 235, 244));
        TextNomePet.setFont(new java.awt.Font("Typo Hoop Demo", 0, 18)); // NOI18N
        TextNomePet.setBorder(null);
        getContentPane().add(TextNomePet, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 270, -1));

        Fundinho2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/FundinhoFino_1.png"))); // NOI18N
        getContentPane().add(Fundinho2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 320, 40));

        JNome3.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        JNome3.setForeground(new java.awt.Color(255, 255, 255));
        JNome3.setText("RAÇA");
        getContentPane().add(JNome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 60, 20));

        TextRaca.setEditable(false);
        TextRaca.setBackground(new java.awt.Color(232, 235, 244));
        TextRaca.setFont(new java.awt.Font("Typo Hoop Demo", 0, 18)); // NOI18N
        TextRaca.setBorder(null);
        getContentPane().add(TextRaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 270, -1));

        Fundinho3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/FundinhoFino_1.png"))); // NOI18N
        getContentPane().add(Fundinho3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 320, -1));

        JNome4.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        JNome4.setForeground(new java.awt.Color(255, 255, 255));
        JNome4.setText("SEXO");
        getContentPane().add(JNome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, 60, 20));

        TextIdadePet.setEditable(false);
        TextIdadePet.setBackground(new java.awt.Color(232, 235, 244));
        TextIdadePet.setFont(new java.awt.Font("Typo Hoop Demo", 0, 18)); // NOI18N
        TextIdadePet.setBorder(null);
        getContentPane().add(TextIdadePet, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 270, -1));

        JNome5.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        JNome5.setForeground(new java.awt.Color(255, 255, 255));
        JNome5.setText("IDADE");
        getContentPane().add(JNome5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, 60, 20));

        Fundinho4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/FundinhoFino_1.png"))); // NOI18N
        getContentPane().add(Fundinho4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 320, 40));

        TextSexo.setEditable(false);
        TextSexo.setBackground(new java.awt.Color(232, 235, 244));
        TextSexo.setFont(new java.awt.Font("Typo Hoop Demo", 0, 18)); // NOI18N
        TextSexo.setBorder(null);
        getContentPane().add(TextSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, 270, -1));

        Fundinho5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/FundinhoFino_1.png"))); // NOI18N
        getContentPane().add(Fundinho5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, 320, -1));

        TextEspecie.setEditable(false);
        TextEspecie.setBackground(new java.awt.Color(232, 235, 244));
        TextEspecie.setFont(new java.awt.Font("Typo Hoop Demo", 0, 18)); // NOI18N
        TextEspecie.setBorder(null);
        getContentPane().add(TextEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, 270, -1));

        Fundinho6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/FundinhoFino_1.png"))); // NOI18N
        getContentPane().add(Fundinho6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, 320, -1));

        JNome6.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        JNome6.setForeground(new java.awt.Color(255, 255, 255));
        JNome6.setText("ESPÉCIE");
        getContentPane().add(JNome6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, 90, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/BotEditar.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 610, 210, 60));

        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DADOS A SEREM EDITADOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(51, 51, 51))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 740, 260));

        BotConferir.setBackground(new java.awt.Color(51, 204, 255));
        BotConferir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BotConferir.setForeground(new java.awt.Color(255, 255, 255));
        BotConferir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/BotConferirPeq.png"))); // NOI18N
        BotConferir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotConferirMouseClicked(evt);
            }
        });
        getContentPane().add(BotConferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 290, 160, 60));

        TelaGeral.setBackground(new java.awt.Color(232, 235, 244));
        TelaGeral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Editar.png"))); // NOI18N
        TelaGeral.setOpaque(true);
        getContentPane().add(TelaGeral, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        TextAnimais.setBackground(new java.awt.Color(232, 235, 244));
        TextAnimais.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        TextAnimais.setForeground(new java.awt.Color(1, 81, 74));
        TextAnimais.setText("EDITAR ANIMAL");
        TextAnimais.setOpaque(true);
        getContentPane().add(TextAnimais, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        BG.setBackground(new java.awt.Color(232, 235, 244));
        BG.setOpaque(true);
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 920, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButClienteActionPerformed

        //Declaração de Objetos
        TelaProprietario screenPrt = new TelaProprietario();

        //Mostrar Tela do Proprietario
        screenPrt.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_ButClienteActionPerformed

    private void ButAnimaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButAnimaisMouseClicked

    }//GEN-LAST:event_ButAnimaisMouseClicked

    private void ButAnimaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAnimaisActionPerformed

        //Declaração de Objetos
        TelaAnimais animaisScreen = new TelaAnimais();

        //Mostrar tela do animal
        animaisScreen.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_ButAnimaisActionPerformed

    private void ButVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButVeterinarioActionPerformed
        //Declaração de Objetos
        TelaLogin t = new TelaLogin();

        //Mostrar tela de vacina
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButVeterinarioActionPerformed

    private void IconeEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconeEditarMouseClicked
        //Declaração de Objetos
        TelaEditarAnimal t = new TelaEditarAnimal();

        //Mostrar tela editar
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IconeEditarMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked

        //Declaração de Objetos
        TelaPrincipal t = new TelaPrincipal();

        //Mostrar tela principal
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeMouseClicked

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked

        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void IconeExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconeExcluirMouseClicked

        //Declaração de Objetos
        TelaDeletarAnimal screenDel = new TelaDeletarAnimal();

        //Mostrando tela principal
        screenDel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IconeExcluirMouseClicked

    private void IconeBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconeBuscarMouseClicked

        //Declaração de Objetos
        BuscarAnimal screenBuscar = new BuscarAnimal();

        //Mostrar tela de Buscar Animal
        screenBuscar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IconeBuscarMouseClicked

    private void IconeCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconeCadastrarMouseClicked

        //Declaração de Objetos
        TelaAnimais animaisScreen = new TelaAnimais();

        //Mostrar tela animal
        animaisScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IconeCadastrarMouseClicked

    private void IconeVacinasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconeVacinasMouseClicked

        //Declaração de Objetos
        TelaVacina screenVac = new TelaVacina();

        //Mostrar tela de vacina
        screenVac.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IconeVacinasMouseClicked

    private void BotConferirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotConferirMouseClicked
        conferir();
    }//GEN-LAST:event_BotConferirMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        editar();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEditarAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JPanel BordaLeft;
    private javax.swing.JPanel BordaTop;
    private javax.swing.JPanel Bordinha;
    private javax.swing.JPanel Bordinha1;
    private javax.swing.JPanel Bordinha2;
    private javax.swing.JLabel BotConferir;
    private javax.swing.JButton ButAnimais;
    private javax.swing.JButton ButCliente;
    private javax.swing.JButton ButVeterinario;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel Fundinho;
    private javax.swing.JLabel Fundinho1;
    private javax.swing.JLabel Fundinho2;
    private javax.swing.JLabel Fundinho3;
    private javax.swing.JLabel Fundinho4;
    private javax.swing.JLabel Fundinho5;
    private javax.swing.JLabel Fundinho6;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel IconVet;
    private javax.swing.JLabel IconeBuscar;
    private javax.swing.JLabel IconeCadastrar;
    private javax.swing.JLabel IconeEditar;
    private javax.swing.JLabel IconeExcluir;
    private javax.swing.JLabel IconeVacinas;
    private javax.swing.JLabel JNome;
    private javax.swing.JLabel JNome1;
    private javax.swing.JLabel JNome2;
    private javax.swing.JLabel JNome3;
    private javax.swing.JLabel JNome4;
    private javax.swing.JLabel JNome5;
    private javax.swing.JLabel JNome6;
    private javax.swing.JLabel NomeVet;
    private javax.swing.JLabel TelaGeral;
    private javax.swing.JLabel TextAnimais;
    private javax.swing.JTextField TextEspecie;
    private javax.swing.JTextField TextIdadePet;
    private javax.swing.JTextField TextNome;
    private javax.swing.JTextField TextNome1;
    private javax.swing.JTextField TextNomePet;
    private javax.swing.JTextField TextRaca;
    private javax.swing.JTextField TextSexo;
    private javax.swing.JPanel Vet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    private void conferir() {

        //Declaração de Objetos
        Animal animal = new Animal();

        //Declaração de variaveis
        int aux;
        int id;
        String nome;
        String nomeD;

        //Atribuição de Valores
        aux = 0;
        nome = TextNome.getText();
        nomeD = TextNome1.getText();
        id = animal.Adao.IdAnimalNome(nome, nomeD);

        for (Animal animalAux : animal.Adao.salvarAnimaisNaLista()) {
            if (animalAux.getNumeroID() == id) {

                //Pegando os valores correspondentes ao id 
                TextNomePet.setText(animalAux.getNome());
                TextIdadePet.setText(Integer.toString(animalAux.getIdade()));
                TextRaca.setText(animalAux.getRaca());
                TextSexo.setText(animalAux.getGenero());
                TextEspecie.setText(animalAux.getEspecie());
                TextNome.setText(animalAux.getNome());

                //Para deixar editavel
                TextNomePet.setEditable(true);
                TextIdadePet.setEditable(true);
                TextRaca.setEditable(true);
                TextSexo.setEditable(true);
                TextEspecie.setEditable(true);

                aux++;

                break;

            } else {
                TextNome.setText(null);
                TextNome1.setText(null);

            }
        }
        if (aux == 0) {
            JOptionPane.showMessageDialog(null, "NÃO ENCONTRADO!");
        }
    }

    private void editar() {

        //Declaração de Objetos
        Animal animal = new Animal();

        //Declaração de variaveis
        int aux;
        int id;
        String nome;
        String nomeD;

        //Atribuição de Valores
        aux = 0;
        nome = TextNome.getText();
        nomeD = TextNome1.getText();
        id = animal.Adao.IdAnimalNome(nome, nomeD);

        //if para caso 
        if (nome.isEmpty()) {

            JOptionPane.showMessageDialog(null, "INVÁLIDO!");

        } else {

            try {

                //Atualizando dados
                animal.Adao.atualizarAnimalEspeciePeloNomeCpf(TextEspecie.getText(), id);
                animal.Adao.atualizarAnimalIdadePeloNomeCpf(TextIdadePet.getText(), id);
                animal.Adao.atualizarAnimalNomePeloNomeCpf(TextNomePet.getText(), id);
                animal.Adao.atualizarAnimalRacaPeloNomeCpf(TextRaca.getText(), id);
                animal.Adao.atualizarAnimalSexoPeloNomeCpf(TextSexo.getText(), id);

                //Deixando as caixas te textos vazias
                TextEspecie.setText(null);
                TextIdadePet.setText(null);
                TextNomePet.setText(null);
                TextRaca.setText(null);
                TextSexo.setText(null);
                TextNome.setText(null);
                TextNome1.setText(null);

                //Para deixar editavel
                TextEspecie.setEditable(false);
                TextNomePet.setEditable(false);
                TextIdadePet.setEditable(false);
                TextRaca.setEditable(false);
                TextSexo.setEditable(false);
                TextNome.setEditable(false);
                TextNome1.setEditable(false);

                //Saida
                JOptionPane.showMessageDialog(null, "Sucesso ao Editar!");

            } catch (NumberFormatException ex) {

                JOptionPane.showMessageDialog(null, "APENAS NUMEROS NA IDADE");

            }

        }
    }

}
