/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.gespet.view;

import javax.swing.JOptionPane;
import br.inatel.gespet.model.Veterinario;
import br.inatel.gespet.control.VeterinarioDAO;

/**
 *
 * @author Brendhon
 */
public class TelaVet extends javax.swing.JFrame {

    /**
     * Creates new form Veterinario
     */
    public TelaVet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextCrmv = new javax.swing.JTextField();
        TextSenha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        IconeUser = new javax.swing.JLabel();
        IconeUser1 = new javax.swing.JLabel();
        Senha = new javax.swing.JLabel();
        User = new javax.swing.JLabel();
        Telinha = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextCrmv.setBackground(new java.awt.Color(232, 235, 244));
        TextCrmv.setBorder(null);
        getContentPane().add(TextCrmv, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 360, 160, 30));

        TextSenha.setBackground(new java.awt.Color(232, 235, 244));
        TextSenha.setBorder(null);
        getContentPane().add(TextSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 150, 30));

        jLabel1.setBackground(new java.awt.Color(232, 235, 244));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/BotCriar.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 530, 170, 60));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Sair2.png"))); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 650, -1, -1));

        IconeUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Senha .png"))); // NOI18N
        getContentPane().add(IconeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, -1, -1));

        IconeUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/User.png"))); // NOI18N
        getContentPane().add(IconeUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, -1, -1));

        Senha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Botao.png"))); // NOI18N
        getContentPane().add(Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, -1, -1));

        User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Botao.png"))); // NOI18N
        getContentPane().add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, -1, -1));

        Telinha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Telinha_1.png"))); // NOI18N
        Telinha.setAlignmentX(360.0F);
        Telinha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Telinha.setVerifyInputWhenFocusTarget(false);
        Telinha.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(Telinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        BG.setBackground(new java.awt.Color(102, 255, 102));
        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/BG_1.png"))); // NOI18N
        BG.setPreferredSize(new java.awt.Dimension(1080, 720));
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1100, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked

        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

        int aux = 0;
        Veterinario vet = new Veterinario();
        TelaLogin screenLogin = new TelaLogin();
        VeterinarioDAO vetDao = new VeterinarioDAO();

        vet.setCrmv(Integer.parseInt(TextCrmv.getText()));
        vet.setSenha(TextSenha.getText());

        for (Veterinario vet2 : vetDao.salvarVeterinarioEmLista()) {

            if (vet2.getCrmv() == Integer.parseInt(TextCrmv.getText())) {
                aux++;
            }

        }
        if (aux == 0) {
            vet.inserirVeterinarios(vet);
        } else {
            JOptionPane.showMessageDialog(null, "VETERINARIO JÁ CADASTRADO!");
        }

        screenLogin.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel IconeUser;
    private javax.swing.JLabel IconeUser1;
    private javax.swing.JLabel Senha;
    private javax.swing.JLabel Telinha;
    private javax.swing.JTextField TextCrmv;
    private javax.swing.JTextField TextSenha;
    private javax.swing.JLabel User;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
