/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.gespet.view;

import java.awt.Color;
import javax.swing.JOptionPane;
import br.inatel.gespet.model.Veterinario;
import br.inatel.gespet.control.VeterinarioDAO;

/**
 *
 * @author gabri
 */
public class TelaLogin extends javax.swing.JFrame {

    //Atributos
    static int crmv = 0;

    //Construtores
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CadastrarLogin = new javax.swing.JLabel();
        EditarLogin = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        TextUsuario1 = new javax.swing.JTextField();
        IconeUser = new javax.swing.JLabel();
        IconeUser1 = new javax.swing.JLabel();
        Senha = new javax.swing.JLabel();
        User = new javax.swing.JLabel();
        ButtonLogar = new javax.swing.JLabel();
        Telinha = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        CadastrarLogin.setBackground(new java.awt.Color(23, 105, 99));
        CadastrarLogin.setFont(new java.awt.Font("Typo Hoop Demo", 1, 14)); // NOI18N
        CadastrarLogin.setForeground(new java.awt.Color(255, 255, 255));
        CadastrarLogin.setText("CRIAR NOVA CONTA");
        CadastrarLogin.setOpaque(true);
        CadastrarLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastrarLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CadastrarLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CadastrarLoginMouseExited(evt);
            }
        });
        jPanel1.add(CadastrarLogin);
        CadastrarLogin.setBounds(450, 580, 140, 19);

        EditarLogin.setBackground(new java.awt.Color(23, 105, 99));
        EditarLogin.setFont(new java.awt.Font("Typo Hoop Demo", 1, 14)); // NOI18N
        EditarLogin.setForeground(new java.awt.Color(255, 255, 255));
        EditarLogin.setText("ESQUECEU A SENHA ?");
        EditarLogin.setOpaque(true);
        EditarLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditarLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditarLoginMouseExited(evt);
            }
        });
        jPanel1.add(EditarLogin);
        EditarLogin.setBounds(450, 490, 160, 19);

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Sair2.png"))); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        jPanel1.add(Exit);
        Exit.setBounds(1020, 650, 50, 60);

        jPasswordField1.setBackground(new java.awt.Color(232, 235, 244));
        jPasswordField1.setBorder(null);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(450, 440, 170, 30);

        TextUsuario1.setBackground(new java.awt.Color(232, 235, 244));
        TextUsuario1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        TextUsuario1.setBorder(null);
        TextUsuario1.setOpaque(false);
        TextUsuario1.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        TextUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextUsuario1ActionPerformed(evt);
            }
        });
        jPanel1.add(TextUsuario1);
        TextUsuario1.setBounds(450, 360, 170, 30);

        IconeUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Senha .png"))); // NOI18N
        jPanel1.add(IconeUser);
        IconeUser.setBounds(420, 440, 23, 30);

        IconeUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/User.png"))); // NOI18N
        jPanel1.add(IconeUser1);
        IconeUser1.setBounds(420, 360, 23, 30);

        Senha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Botao.png"))); // NOI18N
        Senha.setText("jLabel1");
        jPanel1.add(Senha);
        Senha.setBounds(410, 420, 230, 70);

        User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Botao.png"))); // NOI18N
        User.setText("jLabel1");
        jPanel1.add(User);
        User.setBounds(410, 340, 230, 70);

        ButtonLogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Entrar.png"))); // NOI18N
        ButtonLogar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonLogarMouseClicked(evt);
            }
        });
        ButtonLogar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ButtonLogarKeyPressed(evt);
            }
        });
        jPanel1.add(ButtonLogar);
        ButtonLogar.setBounds(460, 510, 130, 70);

        Telinha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Telinha_1.png"))); // NOI18N
        Telinha.setAlignmentX(360.0F);
        Telinha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Telinha.setVerifyInputWhenFocusTarget(false);
        Telinha.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(Telinha);
        Telinha.setBounds(360, 0, 337, 720);

        BG.setBackground(new java.awt.Color(102, 255, 102));
        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/BG_1.png"))); // NOI18N
        jPanel1.add(BG);
        BG.setBounds(-20, 0, 1100, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TextUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextUsuario1ActionPerformed

    //Metodo para logar
    private void ButtonLogarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonLogarMouseClicked

        //Declaração de Objetos
        TelaPrincipal t = new TelaPrincipal();
        Veterinario vet = new Veterinario();

        //Declaração de Variaveis
        String senha;
        int crmvAux;

        //Atribuição de Valores
        try {
            crmvAux = Integer.parseInt(TextUsuario1.getText());
            senha = jPasswordField1.getText();

            //Função login retorna o crmv se ele existir no Banco caso não ele ira retonar 0
            crmv = login(crmvAux, senha);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "APENAS NUMEROS NO CRMV!");
        }

        //IF para
        if (crmv != 0) {
            t.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "VETERINÁRIO NÃO CADASTRADO");
        }
    }//GEN-LAST:event_ButtonLogarMouseClicked

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked

        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void EditarLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarLoginMouseClicked

        //Declaração de Objetos
        TelaEsqueceuSenha t = new TelaEsqueceuSenha();

        //Mostrando tela do esqueceu Senha
        t.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_EditarLoginMouseClicked

    private void EditarLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarLoginMouseEntered
        EditarLogin.setForeground(Color.cyan);
    }//GEN-LAST:event_EditarLoginMouseEntered

    private void EditarLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarLoginMouseExited
        EditarLogin.setForeground(Color.WHITE);
    }//GEN-LAST:event_EditarLoginMouseExited

    private void CadastrarLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarLoginMouseEntered
        CadastrarLogin.setForeground(Color.cyan);
    }//GEN-LAST:event_CadastrarLoginMouseEntered

    private void CadastrarLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarLoginMouseExited
        CadastrarLogin.setForeground(Color.WHITE);
    }//GEN-LAST:event_CadastrarLoginMouseExited

    //CADASTRAR UM NOVO VETERINARIO
    private void CadastrarLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarLoginMouseClicked

        TelaVet screenVet = new TelaVet();

        screenVet.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_CadastrarLoginMouseClicked

    //FAZER O LOGIN
    private void ButtonLogarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ButtonLogarKeyPressed


    }//GEN-LAST:event_ButtonLogarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel ButtonLogar;
    private javax.swing.JLabel CadastrarLogin;
    private javax.swing.JLabel EditarLogin;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel IconeUser;
    private javax.swing.JLabel IconeUser1;
    private javax.swing.JLabel Senha;
    private javax.swing.JLabel Telinha;
    private javax.swing.JTextField TextUsuario1;
    private javax.swing.JLabel User;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables

    //Função Login
    private int login(int crmvL, String senhaL) {

        //Declaração de Objetos
        VeterinarioDAO Vdao = new VeterinarioDAO();

        //Declaração de variaveis
        int aux = 0; //Variavel auxiliar para verificar se o CRMV esta contido no Banco

        //Foreach para varrer lista resultante do salvarVeterinarioEmLista()
        for (Veterinario veterinario : Vdao.salvarVeterinarioEmLista()) {

            //if para mostrar os dados correspondentes ao CRMV passado
            if (veterinario.getCrmv() == crmvL && veterinario.getSenha().contentEquals(senhaL)) {
                aux++;
            }
        }
        if (aux == 0) {
            return 0;
        } else {
            return crmvL;
        }
    }
}
