/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.gespet.view;

import javax.swing.JOptionPane;
import br.inatel.gespet.control.AnimalDAO;
import br.inatel.gespet.model.CarteiraDeVacina;

/**
 *
 * @author Brendhon
 */
public class TelaDeletarAnimal extends javax.swing.JFrame {

    /**
     * Creates new form TelaDeletarAnimal
     */
    public TelaDeletarAnimal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BordaLeft = new javax.swing.JPanel();
        IconVet = new javax.swing.JLabel();
        Vet = new javax.swing.JPanel();
        NomeVet = new javax.swing.JLabel();
        ButCliente = new javax.swing.JButton();
        ButAnimais = new javax.swing.JButton();
        ButDeslogar = new javax.swing.JButton();
        Bordinha = new javax.swing.JPanel();
        Bordinha1 = new javax.swing.JPanel();
        Bordinha2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BordaTop = new javax.swing.JPanel();
        IconeEditar = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        IconeExcluir = new javax.swing.JLabel();
        IconeBuscar = new javax.swing.JLabel();
        IconeCadastrar = new javax.swing.JLabel();
        IconeVacinas1 = new javax.swing.JLabel();
        DeletarTexto = new javax.swing.JLabel();
        JNome = new javax.swing.JLabel();
        TextNome = new javax.swing.JTextField();
        Fundinho = new javax.swing.JLabel();
        TextCPF = new javax.swing.JTextField();
        Fundinho1 = new javax.swing.JLabel();
        JNome1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TelaGeral = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BordaLeft.setBackground(new java.awt.Color(23, 105, 99));
        BordaLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconVet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconVet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Animal.png"))); // NOI18N
        BordaLeft.add(IconVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 130));

        Vet.setBackground(new java.awt.Color(1, 81, 74));

        NomeVet.setBackground(new java.awt.Color(255, 0, 153));
        NomeVet.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        NomeVet.setForeground(new java.awt.Color(255, 255, 255));
        NomeVet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomeVet.setText("NOME VET");
        NomeVet.setAlignmentX(0.5F);

        javax.swing.GroupLayout VetLayout = new javax.swing.GroupLayout(Vet);
        Vet.setLayout(VetLayout);
        VetLayout.setHorizontalGroup(
            VetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
            .addGroup(VetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(NomeVet, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
        );
        VetLayout.setVerticalGroup(
            VetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(VetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(NomeVet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
        );

        BordaLeft.add(Vet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 160, 60));

        ButCliente.setBackground(new java.awt.Color(71, 192, 161));
        ButCliente.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        ButCliente.setForeground(new java.awt.Color(255, 255, 255));
        ButCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Cliente.png"))); // NOI18N
        ButCliente.setText("CLIENTES");
        ButCliente.setBorder(null);
        ButCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButClienteActionPerformed(evt);
            }
        });
        BordaLeft.add(ButCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 150, 100));

        ButAnimais.setBackground(new java.awt.Color(71, 192, 161));
        ButAnimais.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        ButAnimais.setForeground(new java.awt.Color(255, 255, 255));
        ButAnimais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Animal.png"))); // NOI18N
        ButAnimais.setText("ANIMAIS");
        ButAnimais.setBorder(null);
        ButAnimais.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButAnimais.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButAnimais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAnimaisActionPerformed(evt);
            }
        });
        BordaLeft.add(ButAnimais, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 150, 100));

        ButDeslogar.setBackground(new java.awt.Color(71, 192, 161));
        ButDeslogar.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        ButDeslogar.setForeground(new java.awt.Color(255, 255, 255));
        ButDeslogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Sair.png"))); // NOI18N
        ButDeslogar.setText("DESLOGAR");
        ButDeslogar.setBorder(null);
        ButDeslogar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButDeslogar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButDeslogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButDeslogarActionPerformed(evt);
            }
        });
        BordaLeft.add(ButDeslogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 150, 100));

        Bordinha.setBackground(new java.awt.Color(1, 81, 74));

        javax.swing.GroupLayout BordinhaLayout = new javax.swing.GroupLayout(Bordinha);
        Bordinha.setLayout(BordinhaLayout);
        BordinhaLayout.setHorizontalGroup(
            BordinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        BordinhaLayout.setVerticalGroup(
            BordinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        BordaLeft.add(Bordinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 10, -1));

        Bordinha1.setBackground(new java.awt.Color(1, 81, 74));

        javax.swing.GroupLayout Bordinha1Layout = new javax.swing.GroupLayout(Bordinha1);
        Bordinha1.setLayout(Bordinha1Layout);
        Bordinha1Layout.setHorizontalGroup(
            Bordinha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Bordinha1Layout.setVerticalGroup(
            Bordinha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        BordaLeft.add(Bordinha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        Bordinha2.setBackground(new java.awt.Color(1, 81, 74));

        javax.swing.GroupLayout Bordinha2Layout = new javax.swing.GroupLayout(Bordinha2);
        Bordinha2.setLayout(Bordinha2Layout);
        Bordinha2Layout.setHorizontalGroup(
            Bordinha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Bordinha2Layout.setVerticalGroup(
            Bordinha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        BordaLeft.add(Bordinha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Configuracoes.png"))); // NOI18N
        BordaLeft.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 80, 80));

        getContentPane().add(BordaLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 720));

        BordaTop.setBackground(new java.awt.Color(1, 81, 74));
        BordaTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconeEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/IconEditar.png"))); // NOI18N
        IconeEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconeEditarMouseClicked(evt);
            }
        });
        BordaTop.add(IconeEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, 60));

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Home.png"))); // NOI18N
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        BordaTop.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, -1, -1, 90));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/OFF.png"))); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        BordaTop.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, -2, 60, 90));

        IconeExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/IconDeletar.png"))); // NOI18N
        IconeExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconeExcluirMouseClicked(evt);
            }
        });
        BordaTop.add(IconeExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 40, 60));

        IconeBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/IconPesquisar.png"))); // NOI18N
        IconeBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconeBuscarMouseClicked(evt);
            }
        });
        BordaTop.add(IconeBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 50, 60));

        IconeCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/IconCadastrar.png"))); // NOI18N
        IconeCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconeCadastrarMouseClicked(evt);
            }
        });
        BordaTop.add(IconeCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 50, 60));

        IconeVacinas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/IconVacina.png"))); // NOI18N
        IconeVacinas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconeVacinas1MouseClicked(evt);
            }
        });
        BordaTop.add(IconeVacinas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, 80));

        getContentPane().add(BordaTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 990, 90));

        DeletarTexto.setBackground(new java.awt.Color(1, 81, 74));
        DeletarTexto.setFont(new java.awt.Font("Typo Hoop Demo", 1, 36)); // NOI18N
        DeletarTexto.setForeground(new java.awt.Color(1, 81, 74));
        DeletarTexto.setText("DELETAR ANIMAL");
        getContentPane().add(DeletarTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 320, 50));

        JNome.setFont(new java.awt.Font("Typo Hoop Demo", 1, 24)); // NOI18N
        JNome.setForeground(new java.awt.Color(255, 255, 255));
        JNome.setText("NOME");
        getContentPane().add(JNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 80, 30));

        TextNome.setBackground(new java.awt.Color(232, 235, 244));
        TextNome.setFont(new java.awt.Font("Typo Hoop Demo", 0, 24)); // NOI18N
        TextNome.setBorder(null);
        getContentPane().add(TextNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 190, 30));

        Fundinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Botao.png"))); // NOI18N
        getContentPane().add(Fundinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 240, 50));

        TextCPF.setBackground(new java.awt.Color(232, 235, 244));
        TextCPF.setFont(new java.awt.Font("Typo Hoop Demo", 0, 24)); // NOI18N
        TextCPF.setBorder(null);
        getContentPane().add(TextCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 190, 30));

        Fundinho1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Botao.png"))); // NOI18N
        getContentPane().add(Fundinho1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 240, 50));

        JNome1.setFont(new java.awt.Font("Typo Hoop Demo", 1, 24)); // NOI18N
        JNome1.setForeground(new java.awt.Color(255, 255, 255));
        JNome1.setText("CPF");
        getContentPane().add(JNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 80, 30));

        jLabel2.setBackground(new java.awt.Color(1, 81, 74));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/BotDel.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 210, 60));

        TelaGeral.setBackground(new java.awt.Color(232, 235, 244));
        TelaGeral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/JanDeletar.png"))); // NOI18N
        TelaGeral.setOpaque(true);
        getContentPane().add(TelaGeral, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));

        BG.setBackground(new java.awt.Color(232, 235, 244));
        BG.setOpaque(true);
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 920, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButClienteActionPerformed

        //Declaração de Objetos
        TelaProprietario screenPrp = new TelaProprietario();

        //Mostrando Tela inicial
        screenPrp.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_ButClienteActionPerformed

    private void ButAnimaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAnimaisActionPerformed

        //Declaração de Objetos
        TelaAnimais animaisScreen = new TelaAnimais();

        //Mostrar tela do Animal
        animaisScreen.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_ButAnimaisActionPerformed

    private void ButDeslogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButDeslogarActionPerformed

        //Declaração de Objetos
        TelaLogin t = new TelaLogin();

        //Mostrando tela de Login
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButDeslogarActionPerformed

    private void IconeEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconeEditarMouseClicked
        //Declaração de Objetos
        TelaEditarAnimal t = new TelaEditarAnimal();

        //Mostrar tela editar
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IconeEditarMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked

        //Declaração de Objetos
        TelaPrincipal t = new TelaPrincipal();

        //Mostrando tela principal
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeMouseClicked

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked

        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void IconeExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconeExcluirMouseClicked

        //Declaração de Objetos
        TelaDeletarAnimal screenDel = new TelaDeletarAnimal();

        //Mostrando tela principal
        screenDel.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_IconeExcluirMouseClicked

    private void IconeBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconeBuscarMouseClicked

        //Declaração de Objetos
        BuscarAnimal screenBuscar = new BuscarAnimal();

        //Mostrar a tela de Buscar animal
        screenBuscar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IconeBuscarMouseClicked

    private void IconeCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconeCadastrarMouseClicked

        //Declaração de Objetos
        TelaAnimais animaisScreen = new TelaAnimais();

        //Mostrar a tela inicial
        animaisScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IconeCadastrarMouseClicked

    private void IconeVacinas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconeVacinas1MouseClicked
        //Declaração de Objetos
        TelaVacina screenVac = new TelaVacina();

        //Mostrar tela de vacina
        screenVac.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IconeVacinas1MouseClicked

    //CLIQUE NO BOTAO DELETAR
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

        // DELETAR OS DADOS
        deletarAnimal();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeletarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeletarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeletarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeletarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeletarAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JPanel BordaLeft;
    private javax.swing.JPanel BordaTop;
    private javax.swing.JPanel Bordinha;
    private javax.swing.JPanel Bordinha1;
    private javax.swing.JPanel Bordinha2;
    private javax.swing.JButton ButAnimais;
    private javax.swing.JButton ButCliente;
    private javax.swing.JButton ButDeslogar;
    private javax.swing.JLabel DeletarTexto;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel Fundinho;
    private javax.swing.JLabel Fundinho1;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel IconVet;
    private javax.swing.JLabel IconeBuscar;
    private javax.swing.JLabel IconeCadastrar;
    private javax.swing.JLabel IconeEditar;
    private javax.swing.JLabel IconeExcluir;
    private javax.swing.JLabel IconeVacinas1;
    private javax.swing.JLabel JNome;
    private javax.swing.JLabel JNome1;
    private javax.swing.JLabel NomeVet;
    private javax.swing.JLabel TelaGeral;
    private javax.swing.JTextField TextCPF;
    private javax.swing.JTextField TextNome;
    private javax.swing.JPanel Vet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private void telaProprietario() {

    }

    private void telaAnimal() {

    }

    private void deletarAnimal() {

        //Declaração de Objetos
        CarteiraDeVacina carteira = new CarteiraDeVacina();
        AnimalDAO Adao = new AnimalDAO();

        //Declaração de Variaveis
        String nome;
        String cpf;
        boolean resultadoVhasA;
        boolean resultadoCarteira;
        boolean resultado;
        int id;

        //Atribuição de Valores
        nome = TextNome.getText();
        cpf = TextCPF.getText();

        //Pegando o ID referente ao dados passados
        id = Adao.IdAnimal(nome, cpf);

        //Deletando no Banco
        resultadoVhasA = Adao.deleteVhasAPeloID(id); //Deletando tabela originada da relação Veterinario e Animal
        resultadoCarteira = carteira.deletarCarteira(id); //Deletando carteira do animal
        resultado = Adao.deleteAnimalPeloID(id); //Deletando o Animal correspondente ao id

        if (resultadoVhasA && resultado && resultadoCarteira) {

            JOptionPane.showMessageDialog(null, "Sucesso ao Deletar!");

        } else {
            JOptionPane.showMessageDialog(null, "Erro ao Deletar!");
        }
    }
}
