/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.gespet.view;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import br.inatel.gespet.model.Animal;
import br.inatel.gespet.model.PrincipaisInfoAnimal;
import br.inatel.gespet.control.PrincipaisInfoAnimalDAO;
import br.inatel.gespet.model.Proprietario;

/**
 *
 * @author gabri
 */
public class TelaPrincipal extends javax.swing.JFrame {

    boolean listAnimal = false;
    boolean listCliente = false;

    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BordaLeft = new javax.swing.JPanel();
        IconVet = new javax.swing.JLabel();
        Vet = new javax.swing.JPanel();
        NomeVet = new javax.swing.JLabel();
        ButCliente = new javax.swing.JButton();
        ButAnimais = new javax.swing.JButton();
        ButVeterinario = new javax.swing.JButton();
        Bordinha = new javax.swing.JPanel();
        Bordinha1 = new javax.swing.JPanel();
        Bordinha2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BordaTop = new javax.swing.JPanel();
        Home = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        BotLisProp = new javax.swing.JLabel();
        BotLisAnimal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        TelaGeral = new javax.swing.JLabel();
        TextAnimais = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESPET");
        setBackground(new java.awt.Color(60, 63, 63));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BordaLeft.setBackground(new java.awt.Color(23, 105, 99));
        BordaLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconVet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconVet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Animal.png"))); // NOI18N
        BordaLeft.add(IconVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 130));

        Vet.setBackground(new java.awt.Color(1, 81, 74));

        NomeVet.setBackground(new java.awt.Color(255, 0, 153));
        NomeVet.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        NomeVet.setForeground(new java.awt.Color(255, 255, 255));
        NomeVet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomeVet.setText("NOME VET");
        NomeVet.setAlignmentX(0.5F);

        javax.swing.GroupLayout VetLayout = new javax.swing.GroupLayout(Vet);
        Vet.setLayout(VetLayout);
        VetLayout.setHorizontalGroup(
            VetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
            .addGroup(VetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(NomeVet, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
        );
        VetLayout.setVerticalGroup(
            VetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(VetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(NomeVet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
        );

        BordaLeft.add(Vet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 160, 60));

        ButCliente.setBackground(new java.awt.Color(71, 192, 161));
        ButCliente.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        ButCliente.setForeground(new java.awt.Color(255, 255, 255));
        ButCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Cliente.png"))); // NOI18N
        ButCliente.setText("CLIENTES");
        ButCliente.setBorder(null);
        ButCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButClienteActionPerformed(evt);
            }
        });
        BordaLeft.add(ButCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 150, 100));

        ButAnimais.setBackground(new java.awt.Color(71, 192, 161));
        ButAnimais.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        ButAnimais.setForeground(new java.awt.Color(255, 255, 255));
        ButAnimais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Animal.png"))); // NOI18N
        ButAnimais.setText("ANIMAIS");
        ButAnimais.setBorder(null);
        ButAnimais.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButAnimais.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButAnimais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAnimaisActionPerformed(evt);
            }
        });
        BordaLeft.add(ButAnimais, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 150, 100));

        ButVeterinario.setBackground(new java.awt.Color(71, 192, 161));
        ButVeterinario.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        ButVeterinario.setForeground(new java.awt.Color(255, 255, 255));
        ButVeterinario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Sair.png"))); // NOI18N
        ButVeterinario.setText("DESLOGAR");
        ButVeterinario.setBorder(null);
        ButVeterinario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButVeterinario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButVeterinarioActionPerformed(evt);
            }
        });
        BordaLeft.add(ButVeterinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 150, 100));

        Bordinha.setBackground(new java.awt.Color(1, 81, 74));

        javax.swing.GroupLayout BordinhaLayout = new javax.swing.GroupLayout(Bordinha);
        Bordinha.setLayout(BordinhaLayout);
        BordinhaLayout.setHorizontalGroup(
            BordinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        BordinhaLayout.setVerticalGroup(
            BordinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        BordaLeft.add(Bordinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 10, -1));

        Bordinha1.setBackground(new java.awt.Color(1, 81, 74));

        javax.swing.GroupLayout Bordinha1Layout = new javax.swing.GroupLayout(Bordinha1);
        Bordinha1.setLayout(Bordinha1Layout);
        Bordinha1Layout.setHorizontalGroup(
            Bordinha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Bordinha1Layout.setVerticalGroup(
            Bordinha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        BordaLeft.add(Bordinha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        Bordinha2.setBackground(new java.awt.Color(1, 81, 74));

        javax.swing.GroupLayout Bordinha2Layout = new javax.swing.GroupLayout(Bordinha2);
        Bordinha2.setLayout(Bordinha2Layout);
        Bordinha2Layout.setHorizontalGroup(
            Bordinha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Bordinha2Layout.setVerticalGroup(
            Bordinha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        BordaLeft.add(Bordinha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Configuracoes.png"))); // NOI18N
        BordaLeft.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 80, 80));

        getContentPane().add(BordaLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 720));

        BordaTop.setBackground(new java.awt.Color(1, 81, 74));
        BordaTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Home.png"))); // NOI18N
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        BordaTop.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, -1, -1));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/OFF.png"))); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        BordaTop.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, -1, -1));

        getContentPane().add(BordaTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 990, 90));

        BotLisProp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/BotProp.png"))); // NOI18N
        BotLisProp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotLisPropMouseClicked(evt);
            }
        });
        getContentPane().add(BotLisProp, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 270, 60));

        BotLisAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/BotAnimal.png"))); // NOI18N
        BotLisAnimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotLisAnimalMouseClicked(evt);
            }
        });
        getContentPane().add(BotLisAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 200, 70));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("RESULTADO DA BUSCA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 240, -1));

        jScrollPane1.setBorder(null);

        jTextPane1.setBackground(new java.awt.Color(232, 235, 244));
        jTextPane1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 710, 300));

        TelaGeral.setBackground(new java.awt.Color(232, 235, 244));
        TelaGeral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Buscar.png"))); // NOI18N
        TelaGeral.setOpaque(true);
        getContentPane().add(TelaGeral, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        TextAnimais.setBackground(new java.awt.Color(232, 235, 244));
        TextAnimais.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        TextAnimais.setForeground(new java.awt.Color(1, 81, 74));
        TextAnimais.setText("ANIMAIS");
        TextAnimais.setOpaque(true);
        getContentPane().add(TextAnimais, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        BG.setBackground(new java.awt.Color(232, 235, 244));
        BG.setOpaque(true);
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 920, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButClienteActionPerformed
        //Declaração de Objetos
        TelaProprietario t = new TelaProprietario();

        //Mostrar tela de vacina
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButClienteActionPerformed

    private void ButAnimaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAnimaisActionPerformed

        //Declaração de Objetos
        TelaAnimais animaisScreen = new TelaAnimais();

        //Mostrar tela Animal
        animaisScreen.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_ButAnimaisActionPerformed

    private void ButVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButVeterinarioActionPerformed
        //Declaração de Objetos
        TelaLogin t = new TelaLogin();

        //Mostrar tela de vacina
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButVeterinarioActionPerformed

    //METODO PARA IR PARA A TELA INCIAL
    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked

    }//GEN-LAST:event_HomeMouseClicked

    //METODO PARA FECHAR TUDO
    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked

        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void BotLisPropMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotLisPropMouseClicked

        listarCliente();

    }//GEN-LAST:event_BotLisPropMouseClicked

    private void BotLisAnimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotLisAnimalMouseClicked

        listarAnimal();

    }//GEN-LAST:event_BotLisAnimalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JPanel BordaLeft;
    private javax.swing.JPanel BordaTop;
    private javax.swing.JPanel Bordinha;
    private javax.swing.JPanel Bordinha1;
    private javax.swing.JPanel Bordinha2;
    private javax.swing.JLabel BotLisAnimal;
    private javax.swing.JLabel BotLisProp;
    private javax.swing.JButton ButAnimais;
    private javax.swing.JButton ButCliente;
    private javax.swing.JButton ButVeterinario;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel IconVet;
    private javax.swing.JLabel NomeVet;
    private javax.swing.JLabel TelaGeral;
    private javax.swing.JLabel TextAnimais;
    private javax.swing.JPanel Vet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    private void listarAnimal() {

        //Declaração de Objetos
        PrincipaisInfoAnimalDAO Pdao = new PrincipaisInfoAnimalDAO();

        ArrayList<PrincipaisInfoAnimal> info;

        info = Pdao.salvarInfoNaLista();

        jTextPane1.setContentType("String");
        
        //Foreach para varrer e mostrar toda lista resultante do salvarInfoNaLista()
        for (int i = 0; i < Pdao.salvarInfoNaLista().size(); i++) {
            jTextPane1.setText("Nome: " + info.get(i).getNomeDoAnimal() + "\nIdade: " + info.get(i).getIdadeDoAnimal() + "\nSexo: " + info.get(i).getGeneroDoAnimal()
                    + "\nEspecie: " + info.get(i).getEspecieDoAnimal() + "\nRaça: " + info.get(i).getRacaDoAnimal() + "\n__________________\n");
        }
    
}

    private void listarCliente() {
        
        //Declaração de Objetos
        PrincipaisInfoAnimalDAO Pdao = new PrincipaisInfoAnimalDAO();
        Proprietario proprietario = new Proprietario();

        jTextPane1.setContentType("String");

        //Foreach para varrer e mostrar toda lista resultante do salvarInfoNaLista()
        for (Proprietario proprietarios : proprietario.Pdao.buscarUsuariosSemFiltro()) {

            jTextPane1.setText("CPF: " + proprietarios.getCpf()+ "\nNOME: " + proprietarios.getNome()+ "\nCELULAR: " + proprietarios.getCelular()
                    + "\nRUA: " + proprietarios.getRua()+ "\nBAIRRO: " + proprietarios.getBairro()+ "\n____________________\n");

        }

    }

}
