/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.gespet.view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import br.inatel.gespet.model.Animal;
import br.inatel.gespet.model.Vacina;
import br.inatel.gespet.control.VacinaDAO;

/**
 *
 * @author Brendhon
 */
public class TelaVacina extends javax.swing.JFrame {

    static int posicao = 0;

    public TelaVacina() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BordaLeft = new javax.swing.JPanel();
        IconVet = new javax.swing.JLabel();
        Vet = new javax.swing.JPanel();
        NomeVet = new javax.swing.JLabel();
        ButCliente = new javax.swing.JButton();
        ButAnimais = new javax.swing.JButton();
        ButVeterinario = new javax.swing.JButton();
        Bordinha = new javax.swing.JPanel();
        Bordinha1 = new javax.swing.JPanel();
        Bordinha2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BordaTop = new javax.swing.JPanel();
        IconeEditar = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        IconeExcluir = new javax.swing.JLabel();
        IconeBuscar = new javax.swing.JLabel();
        IconeCadastrar = new javax.swing.JLabel();
        IconeVacinas1 = new javax.swing.JLabel();
        TextNomePet = new javax.swing.JTextField();
        TextCpf = new javax.swing.JTextField();
        TextNomeVacina = new javax.swing.JTextField();
        JNome9 = new javax.swing.JLabel();
        TextNomePet1 = new javax.swing.JTextField();
        Fundinho9 = new javax.swing.JLabel();
        JNome10 = new javax.swing.JLabel();
        TextCpf1 = new javax.swing.JTextField();
        BotBuscarVac = new javax.swing.JLabel();
        TextNomeVacina2 = new javax.swing.JTextField();
        TextDataVac = new javax.swing.JTextField();
        Fundinho7 = new javax.swing.JLabel();
        Fundinho18 = new javax.swing.JLabel();
        JNome18 = new javax.swing.JLabel();
        TextDataProxVac = new javax.swing.JTextField();
        Fundinho8 = new javax.swing.JLabel();
        BotAnterior = new javax.swing.JLabel();
        BotProx = new javax.swing.JLabel();
        Fundinho10 = new javax.swing.JLabel();
        VacinaTexto = new javax.swing.JLabel();
        Fundinho = new javax.swing.JLabel();
        JNome = new javax.swing.JLabel();
        JNome1 = new javax.swing.JLabel();
        JNome2 = new javax.swing.JLabel();
        Fundinho2 = new javax.swing.JLabel();
        Fundinho5 = new javax.swing.JLabel();
        JNome5 = new javax.swing.JLabel();
        JNome6 = new javax.swing.JLabel();
        BotAddVac = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NovaVac = new javax.swing.JLabel();
        JNome11 = new javax.swing.JLabel();
        TextNomeVacina1 = new javax.swing.JTextField();
        Fundinho11 = new javax.swing.JLabel();
        TextDia1 = new javax.swing.JTextField();
        Fundinho12 = new javax.swing.JLabel();
        Fundinho13 = new javax.swing.JLabel();
        TextMes1 = new javax.swing.JTextField();
        TextAno1 = new javax.swing.JTextField();
        TextDataProxVac1 = new javax.swing.JTextField();
        Fundinho22 = new javax.swing.JLabel();
        JNome7 = new javax.swing.JLabel();
        TextDataVac1 = new javax.swing.JTextField();
        JNome3 = new javax.swing.JLabel();
        Fundinho23 = new javax.swing.JLabel();
        Fundinho14 = new javax.swing.JLabel();
        JNome12 = new javax.swing.JLabel();
        JNome13 = new javax.swing.JLabel();
        BordaProxVac = new javax.swing.JLabel();
        BordaVacina = new javax.swing.JLabel();
        CarteiraVac = new javax.swing.JLabel();
        JNome14 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BordaLeft.setBackground(new java.awt.Color(23, 105, 99));
        BordaLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconVet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconVet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Animal.png"))); // NOI18N
        BordaLeft.add(IconVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 130));

        Vet.setBackground(new java.awt.Color(1, 81, 74));

        NomeVet.setBackground(new java.awt.Color(255, 0, 153));
        NomeVet.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        NomeVet.setForeground(new java.awt.Color(255, 255, 255));
        NomeVet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomeVet.setText("NOME VET");
        NomeVet.setAlignmentX(0.5F);

        javax.swing.GroupLayout VetLayout = new javax.swing.GroupLayout(Vet);
        Vet.setLayout(VetLayout);
        VetLayout.setHorizontalGroup(
            VetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
            .addGroup(VetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(NomeVet, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
        );
        VetLayout.setVerticalGroup(
            VetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(VetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(NomeVet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
        );

        BordaLeft.add(Vet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 160, 60));

        ButCliente.setBackground(new java.awt.Color(71, 192, 161));
        ButCliente.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        ButCliente.setForeground(new java.awt.Color(255, 255, 255));
        ButCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Cliente.png"))); // NOI18N
        ButCliente.setText("CLIENTES");
        ButCliente.setBorder(null);
        ButCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButClienteActionPerformed(evt);
            }
        });
        BordaLeft.add(ButCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 150, 100));

        ButAnimais.setBackground(new java.awt.Color(71, 192, 161));
        ButAnimais.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        ButAnimais.setForeground(new java.awt.Color(255, 255, 255));
        ButAnimais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Animal.png"))); // NOI18N
        ButAnimais.setText("ANIMAIS");
        ButAnimais.setBorder(null);
        ButAnimais.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButAnimais.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButAnimais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAnimaisActionPerformed(evt);
            }
        });
        BordaLeft.add(ButAnimais, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 150, 100));

        ButVeterinario.setBackground(new java.awt.Color(71, 192, 161));
        ButVeterinario.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        ButVeterinario.setForeground(new java.awt.Color(255, 255, 255));
        ButVeterinario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Sair.png"))); // NOI18N
        ButVeterinario.setText("DESLOGAR");
        ButVeterinario.setBorder(null);
        ButVeterinario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButVeterinario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButVeterinarioActionPerformed(evt);
            }
        });
        BordaLeft.add(ButVeterinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 150, 100));

        Bordinha.setBackground(new java.awt.Color(1, 81, 74));

        javax.swing.GroupLayout BordinhaLayout = new javax.swing.GroupLayout(Bordinha);
        Bordinha.setLayout(BordinhaLayout);
        BordinhaLayout.setHorizontalGroup(
            BordinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        BordinhaLayout.setVerticalGroup(
            BordinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        BordaLeft.add(Bordinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 10, -1));

        Bordinha1.setBackground(new java.awt.Color(1, 81, 74));

        javax.swing.GroupLayout Bordinha1Layout = new javax.swing.GroupLayout(Bordinha1);
        Bordinha1.setLayout(Bordinha1Layout);
        Bordinha1Layout.setHorizontalGroup(
            Bordinha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Bordinha1Layout.setVerticalGroup(
            Bordinha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        BordaLeft.add(Bordinha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        Bordinha2.setBackground(new java.awt.Color(1, 81, 74));

        javax.swing.GroupLayout Bordinha2Layout = new javax.swing.GroupLayout(Bordinha2);
        Bordinha2.setLayout(Bordinha2Layout);
        Bordinha2Layout.setHorizontalGroup(
            Bordinha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Bordinha2Layout.setVerticalGroup(
            Bordinha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        BordaLeft.add(Bordinha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Configuracoes.png"))); // NOI18N
        BordaLeft.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 80, 80));

        getContentPane().add(BordaLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 720));

        BordaTop.setBackground(new java.awt.Color(1, 81, 74));
        BordaTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconeEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/IconEditar.png"))); // NOI18N
        IconeEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconeEditarMouseClicked(evt);
            }
        });
        BordaTop.add(IconeEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, 60));

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Home.png"))); // NOI18N
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        BordaTop.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, -1, -1, 90));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/OFF.png"))); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        BordaTop.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, -2, 60, 90));

        IconeExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/IconDeletar.png"))); // NOI18N
        IconeExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconeExcluirMouseClicked(evt);
            }
        });
        BordaTop.add(IconeExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 40, 60));

        IconeBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/IconPesquisar.png"))); // NOI18N
        IconeBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconeBuscarMouseClicked(evt);
            }
        });
        BordaTop.add(IconeBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 50, 60));

        IconeCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/IconCadastrar.png"))); // NOI18N
        IconeCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconeCadastrarMouseClicked(evt);
            }
        });
        BordaTop.add(IconeCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 50, 60));

        IconeVacinas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/IconVacina.png"))); // NOI18N
        IconeVacinas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconeVacinas1MouseClicked(evt);
            }
        });
        BordaTop.add(IconeVacinas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, 80));

        getContentPane().add(BordaTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 990, 90));

        TextNomePet.setBackground(new java.awt.Color(232, 235, 244));
        TextNomePet.setFont(new java.awt.Font("Typo Hoop Demo", 0, 18)); // NOI18N
        TextNomePet.setBorder(null);
        getContentPane().add(TextNomePet, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 270, -1));

        TextCpf.setBackground(new java.awt.Color(232, 235, 244));
        TextCpf.setFont(new java.awt.Font("Typo Hoop Demo", 0, 18)); // NOI18N
        TextCpf.setBorder(null);
        getContentPane().add(TextCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 270, -1));

        TextNomeVacina.setBackground(new java.awt.Color(232, 235, 244));
        TextNomeVacina.setFont(new java.awt.Font("Typo Hoop Demo", 0, 18)); // NOI18N
        TextNomeVacina.setBorder(null);
        getContentPane().add(TextNomeVacina, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 210, -1));

        JNome9.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        JNome9.setForeground(new java.awt.Color(255, 255, 255));
        JNome9.setText("NOME");
        getContentPane().add(JNome9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 220, 80, -1));

        TextNomePet1.setBackground(new java.awt.Color(232, 235, 244));
        TextNomePet1.setFont(new java.awt.Font("Typo Hoop Demo", 0, 18)); // NOI18N
        TextNomePet1.setBorder(null);
        getContentPane().add(TextNomePet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 270, -1));

        Fundinho9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/FundinhoFino_1.png"))); // NOI18N
        getContentPane().add(Fundinho9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 320, 40));

        JNome10.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        JNome10.setForeground(new java.awt.Color(255, 255, 255));
        JNome10.setText("NOME PROPRIETÁRIO");
        getContentPane().add(JNome10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, 200, 20));

        TextCpf1.setBackground(new java.awt.Color(232, 235, 244));
        TextCpf1.setFont(new java.awt.Font("Typo Hoop Demo", 0, 18)); // NOI18N
        TextCpf1.setBorder(null);
        TextCpf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCpf1ActionPerformed(evt);
            }
        });
        getContentPane().add(TextCpf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 270, -1));

        BotBuscarVac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/BotBuscar_1_1.png"))); // NOI18N
        BotBuscarVac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotBuscarVacMouseClicked(evt);
            }
        });
        getContentPane().add(BotBuscarVac, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, 200, 60));

        TextNomeVacina2.setEditable(false);
        TextNomeVacina2.setBackground(new java.awt.Color(232, 235, 244));
        TextNomeVacina2.setFont(new java.awt.Font("Typo Hoop Demo", 0, 18)); // NOI18N
        TextNomeVacina2.setBorder(null);
        TextNomeVacina2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNomeVacina2ActionPerformed(evt);
            }
        });
        getContentPane().add(TextNomeVacina2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 410, 210, -1));

        TextDataVac.setBackground(new java.awt.Color(232, 235, 244));
        TextDataVac.setFont(new java.awt.Font("Typo Hoop Demo", 0, 18)); // NOI18N
        TextDataVac.setBorder(null);
        getContentPane().add(TextDataVac, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 210, -1));

        Fundinho7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/FundinhoFino2_1.png"))); // NOI18N
        getContentPane().add(Fundinho7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 240, 40));

        Fundinho18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/FundinhoFino2_1.png"))); // NOI18N
        getContentPane().add(Fundinho18, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, 240, 40));

        JNome18.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        JNome18.setForeground(new java.awt.Color(255, 255, 255));
        JNome18.setText("NOME");
        getContentPane().add(JNome18, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 410, 60, 20));

        TextDataProxVac.setBackground(new java.awt.Color(232, 235, 244));
        TextDataProxVac.setFont(new java.awt.Font("Typo Hoop Demo", 0, 18)); // NOI18N
        TextDataProxVac.setBorder(null);
        getContentPane().add(TextDataProxVac, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 210, -1));

        Fundinho8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/FundinhoFino2_1.png"))); // NOI18N
        getContentPane().add(Fundinho8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 240, 40));

        BotAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/SetaLeft.png"))); // NOI18N
        BotAnterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotAnteriorMouseClicked(evt);
            }
        });
        getContentPane().add(BotAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 600, -1, 50));

        BotProx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/SetaRight.png"))); // NOI18N
        BotProx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotProxMouseClicked(evt);
            }
        });
        getContentPane().add(BotProx, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 600, -1, 50));

        Fundinho10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/FundinhoFino_1.png"))); // NOI18N
        getContentPane().add(Fundinho10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 320, -1));

        VacinaTexto.setBackground(new java.awt.Color(1, 81, 74));
        VacinaTexto.setFont(new java.awt.Font("Typo Hoop Demo", 1, 36)); // NOI18N
        VacinaTexto.setForeground(new java.awt.Color(1, 81, 74));
        VacinaTexto.setText("VACINA");
        getContentPane().add(VacinaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 220, 50));

        Fundinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/FundinhoFino_1.png"))); // NOI18N
        getContentPane().add(Fundinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 320, 40));

        JNome.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        JNome.setForeground(new java.awt.Color(255, 255, 255));
        JNome.setText("NOME");
        getContentPane().add(JNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 80, -1));

        JNome1.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        JNome1.setForeground(new java.awt.Color(255, 255, 255));
        JNome1.setText("CPF PROPRIETÁRIO");
        getContentPane().add(JNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 180, 20));

        JNome2.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        JNome2.setForeground(new java.awt.Color(255, 255, 255));
        JNome2.setText("DATA DE VACINAÇÃO");
        getContentPane().add(JNome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 220, 20));

        Fundinho2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/FundinhoFino_1.png"))); // NOI18N
        getContentPane().add(Fundinho2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 320, -1));

        Fundinho5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/FundinhoFino2_1.png"))); // NOI18N
        getContentPane().add(Fundinho5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 240, 40));

        JNome5.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        JNome5.setForeground(new java.awt.Color(255, 255, 255));
        JNome5.setText("NOME");
        getContentPane().add(JNome5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 60, 20));

        JNome6.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        JNome6.setForeground(new java.awt.Color(255, 255, 255));
        JNome6.setText("DATA DA PRÓXIMA VACINA");
        getContentPane().add(JNome6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 260, 20));

        BotAddVac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/BotAdicionar_1.png"))); // NOI18N
        BotAddVac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotAddVacMouseClicked(evt);
            }
        });
        getContentPane().add(BotAddVac, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 580, 210, 60));

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRÓXIMA VACINA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 360, 100));

        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VACINA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 380, 240));

        NovaVac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/NovaVacina_3.png"))); // NOI18N
        getContentPane().add(NovaVac, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 410, 510));

        JNome11.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        JNome11.setForeground(new java.awt.Color(255, 255, 255));
        JNome11.setText("NOME");
        getContentPane().add(JNome11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 60, 20));

        TextNomeVacina1.setBackground(new java.awt.Color(232, 235, 244));
        TextNomeVacina1.setFont(new java.awt.Font("Typo Hoop Demo", 0, 18)); // NOI18N
        TextNomeVacina1.setText("MEL");
        TextNomeVacina1.setBorder(null);
        getContentPane().add(TextNomeVacina1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 210, -1));

        Fundinho11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/FundinhoFino2_1.png"))); // NOI18N
        getContentPane().add(Fundinho11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 240, 40));

        TextDia1.setBackground(new java.awt.Color(232, 235, 244));
        TextDia1.setFont(new java.awt.Font("Typo Hoop Demo", 0, 18)); // NOI18N
        TextDia1.setText("13");
        TextDia1.setToolTipText("");
        TextDia1.setBorder(null);
        TextDia1.setOpaque(false);
        TextDia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDia1ActionPerformed(evt);
            }
        });
        getContentPane().add(TextDia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 30, 40));

        Fundinho12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/FundoDia.png"))); // NOI18N
        getContentPane().add(Fundinho12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 100, -1));

        Fundinho13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/FundoDia.png"))); // NOI18N
        getContentPane().add(Fundinho13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 100, -1));

        TextMes1.setBackground(new java.awt.Color(232, 235, 244));
        TextMes1.setFont(new java.awt.Font("Typo Hoop Demo", 0, 18)); // NOI18N
        TextMes1.setText("13");
        TextMes1.setToolTipText("");
        TextMes1.setBorder(null);
        TextMes1.setOpaque(false);
        TextMes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextMes1ActionPerformed(evt);
            }
        });
        getContentPane().add(TextMes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 20, 40));

        TextAno1.setBackground(new java.awt.Color(232, 235, 244));
        TextAno1.setFont(new java.awt.Font("Typo Hoop Demo", 0, 18)); // NOI18N
        TextAno1.setText("2019");
        TextAno1.setToolTipText("");
        TextAno1.setBorder(null);
        TextAno1.setOpaque(false);
        TextAno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextAno1ActionPerformed(evt);
            }
        });
        getContentPane().add(TextAno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 60, 40));

        TextDataProxVac1.setEditable(false);
        TextDataProxVac1.setBackground(new java.awt.Color(232, 235, 244));
        TextDataProxVac1.setFont(new java.awt.Font("Typo Hoop Demo", 0, 18)); // NOI18N
        TextDataProxVac1.setBorder(null);
        getContentPane().add(TextDataProxVac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 560, 210, -1));

        Fundinho22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/FundinhoFino2_1.png"))); // NOI18N
        getContentPane().add(Fundinho22, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 550, 240, 40));

        JNome7.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        JNome7.setForeground(new java.awt.Color(255, 255, 255));
        JNome7.setText("DATA DA PRÓXIMA VACINA");
        getContentPane().add(JNome7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 530, 260, 20));

        TextDataVac1.setEditable(false);
        TextDataVac1.setBackground(new java.awt.Color(232, 235, 244));
        TextDataVac1.setFont(new java.awt.Font("Typo Hoop Demo", 0, 18)); // NOI18N
        TextDataVac1.setBorder(null);
        getContentPane().add(TextDataVac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 470, 210, -1));

        JNome3.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        JNome3.setForeground(new java.awt.Color(255, 255, 255));
        JNome3.setText("DATA DE VACINAÇÃO");
        getContentPane().add(JNome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, 220, 20));

        Fundinho23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/FundinhoFino2_1.png"))); // NOI18N
        getContentPane().add(Fundinho23, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, 240, 40));

        Fundinho14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/FundoMes.png"))); // NOI18N
        getContentPane().add(Fundinho14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 120, -1));

        JNome12.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        JNome12.setForeground(new java.awt.Color(255, 255, 255));
        JNome12.setText("ANO");
        getContentPane().add(JNome12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 50, 20));

        JNome13.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        JNome13.setForeground(new java.awt.Color(255, 255, 255));
        JNome13.setText("MES");
        getContentPane().add(JNome13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 40, 20));

        BordaProxVac.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRÓXIMA VACINA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        getContentPane().add(BordaProxVac, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, 360, 90));

        BordaVacina.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VACINA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        getContentPane().add(BordaVacina, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 380, 220));

        CarteiraVac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/CarteiraVacina_3.png"))); // NOI18N
        getContentPane().add(CarteiraVac, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 400, 510));

        JNome14.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        JNome14.setForeground(new java.awt.Color(255, 255, 255));
        JNome14.setText("DIA");
        getContentPane().add(JNome14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 40, 20));

        BG.setBackground(new java.awt.Color(232, 235, 244));
        BG.setOpaque(true);
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 920, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButClienteActionPerformed
        telaProprietario();
    }//GEN-LAST:event_ButClienteActionPerformed

    private void ButAnimaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAnimaisActionPerformed

        //Declaração de Objetos
        TelaAnimais animaisScreen = new TelaAnimais();

        //Mostrar a tela do Animal
        animaisScreen.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_ButAnimaisActionPerformed

    private void ButVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButVeterinarioActionPerformed
        //Declaração de Objetos
        TelaLogin t = new TelaLogin();

        //Mostrar tela de vacina
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButVeterinarioActionPerformed

    private void IconeEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconeEditarMouseClicked

        //Declaração de Objetos
        TelaEditarAnimal t = new TelaEditarAnimal();

        //Mostrar tela editar
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IconeEditarMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked

        TelaPrincipal t = new TelaPrincipal();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeMouseClicked

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked

        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void IconeExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconeExcluirMouseClicked

        //Declaração de Objetos
        TelaDeletarAnimal screenDel = new TelaDeletarAnimal();

        //Mostrando tela principal
        screenDel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IconeExcluirMouseClicked

    private void IconeBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconeBuscarMouseClicked

        BuscarAnimal screenBuscar = new BuscarAnimal();
        screenBuscar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IconeBuscarMouseClicked

    private void IconeCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconeCadastrarMouseClicked

        TelaAnimais animaisScreen = new TelaAnimais();
        //Pedindo para mostrar a tela inicial
        animaisScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IconeCadastrarMouseClicked

    private void IconeVacinas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconeVacinas1MouseClicked
        //Declaração de Objetos
        TelaVacina screenVac = new TelaVacina();

        //Mostrar tela de vacina
        screenVac.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IconeVacinas1MouseClicked

    private void TextDia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDia1ActionPerformed

    private void TextMes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextMes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextMes1ActionPerformed

    private void TextAno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextAno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextAno1ActionPerformed

    private void TextCpf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCpf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCpf1ActionPerformed

    private void BotAddVacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotAddVacMouseClicked

        adicionarVacina();

    }//GEN-LAST:event_BotAddVacMouseClicked

    private void BotBuscarVacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotBuscarVacMouseClicked

        mostrarCarteira();

    }//GEN-LAST:event_BotBuscarVacMouseClicked

    //vacina anterior
    private void BotAnteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotAnteriorMouseClicked

        Animal animal = new Animal();
        Vacina vacina = new Vacina();

        //Atribuição de Valores
        String nome = TextNomePet1.getText();
        String nomeD = TextCpf1.getText();
        int id = animal.Adao.IdAnimalNome(nome, nomeD);

        //Declação da Lista
        ArrayList<Vacina> listaDeVacinas = vacina.Vdao.salvarVacinaNaLista(id);

        if (posicao == 0) {
            posicao = 0;
        } else {
            posicao = posicao - 1;
        }
        TextNomeVacina2.setText(listaDeVacinas.get(posicao).getNome());
        TextDataVac1.setText(listaDeVacinas.get(posicao).getDataVacina());
        TextDataProxVac1.setText(listaDeVacinas.get(posicao).getDataProximaVacina());
    }//GEN-LAST:event_BotAnteriorMouseClicked

    //proxima vacina
    private void BotProxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotProxMouseClicked

        Animal animal = new Animal();
        Vacina vacina = new Vacina();

        //Atribuição de Valores
        String nome = TextNomePet1.getText();
        String nomeD = TextCpf1.getText();
        int id = animal.Adao.IdAnimalNome(nome, nomeD);

        //Declação da Lista
        ArrayList<Vacina> listaDeVacinas = vacina.Vdao.salvarVacinaNaLista(id);

        if (posicao == listaDeVacinas.size() - 1) {
            posicao = 0;
        } else {
            posicao = posicao + 1;
        }
        TextNomeVacina2.setText(listaDeVacinas.get(posicao).getNome());
        TextDataVac1.setText(listaDeVacinas.get(posicao).getDataVacina());
        TextDataProxVac1.setText(listaDeVacinas.get(posicao).getDataProximaVacina());
    }//GEN-LAST:event_BotProxMouseClicked

    private void TextNomeVacina2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNomeVacina2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNomeVacina2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVacina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JPanel BordaLeft;
    private javax.swing.JLabel BordaProxVac;
    private javax.swing.JPanel BordaTop;
    private javax.swing.JLabel BordaVacina;
    private javax.swing.JPanel Bordinha;
    private javax.swing.JPanel Bordinha1;
    private javax.swing.JPanel Bordinha2;
    private javax.swing.JLabel BotAddVac;
    private javax.swing.JLabel BotAnterior;
    private javax.swing.JLabel BotBuscarVac;
    private javax.swing.JLabel BotProx;
    private javax.swing.JButton ButAnimais;
    private javax.swing.JButton ButCliente;
    private javax.swing.JButton ButVeterinario;
    private javax.swing.JLabel CarteiraVac;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel Fundinho;
    private javax.swing.JLabel Fundinho10;
    private javax.swing.JLabel Fundinho11;
    private javax.swing.JLabel Fundinho12;
    private javax.swing.JLabel Fundinho13;
    private javax.swing.JLabel Fundinho14;
    private javax.swing.JLabel Fundinho18;
    private javax.swing.JLabel Fundinho2;
    private javax.swing.JLabel Fundinho22;
    private javax.swing.JLabel Fundinho23;
    private javax.swing.JLabel Fundinho5;
    private javax.swing.JLabel Fundinho7;
    private javax.swing.JLabel Fundinho8;
    private javax.swing.JLabel Fundinho9;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel IconVet;
    private javax.swing.JLabel IconeBuscar;
    private javax.swing.JLabel IconeCadastrar;
    private javax.swing.JLabel IconeEditar;
    private javax.swing.JLabel IconeExcluir;
    private javax.swing.JLabel IconeVacinas1;
    private javax.swing.JLabel JNome;
    private javax.swing.JLabel JNome1;
    private javax.swing.JLabel JNome10;
    private javax.swing.JLabel JNome11;
    private javax.swing.JLabel JNome12;
    private javax.swing.JLabel JNome13;
    private javax.swing.JLabel JNome14;
    private javax.swing.JLabel JNome18;
    private javax.swing.JLabel JNome2;
    private javax.swing.JLabel JNome3;
    private javax.swing.JLabel JNome5;
    private javax.swing.JLabel JNome6;
    private javax.swing.JLabel JNome7;
    private javax.swing.JLabel JNome9;
    private javax.swing.JLabel NomeVet;
    private javax.swing.JLabel NovaVac;
    private javax.swing.JTextField TextAno1;
    private javax.swing.JTextField TextCpf;
    private javax.swing.JTextField TextCpf1;
    private javax.swing.JTextField TextDataProxVac;
    private javax.swing.JTextField TextDataProxVac1;
    private javax.swing.JTextField TextDataVac;
    private javax.swing.JTextField TextDataVac1;
    private javax.swing.JTextField TextDia1;
    private javax.swing.JTextField TextMes1;
    private javax.swing.JTextField TextNomePet;
    private javax.swing.JTextField TextNomePet1;
    private javax.swing.JTextField TextNomeVacina;
    private javax.swing.JTextField TextNomeVacina1;
    private javax.swing.JTextField TextNomeVacina2;
    private javax.swing.JLabel VacinaTexto;
    private javax.swing.JPanel Vet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    private void ScreenVacina() {

        TelaVacina screenVac = new TelaVacina();
        screenVac.setVisible(true);
        this.dispose();

    }

    private void telaProprietario() {

        //Declaração de Objetos
        TelaProprietario screenPrp = new TelaProprietario();

        //Mostrando Tela do Proprietario
        screenPrp.setVisible(true);
        this.dispose();

    }

    private void adicionarVacina() {

        //Delcaração de Objetos
        Vacina novaVacina = new Vacina();
        VacinaDAO Vdao = new VacinaDAO();
        Animal animal = new Animal();

        //Declaração de Variáveis
        String nomeA;
        String nome;
        String cpfD;
        String data;
        String dataProx;
        int idAnimal;
        boolean resultado;

        //Atribuição de Valores
        nomeA = TextNomePet.getText();
        cpfD = TextCpf.getText();
        idAnimal = animal.Adao.IdAnimal(nomeA, cpfD); //Pegando o ID do animal referente ao nome e o cpf
        nome = TextNomeVacina.getText();
        data = TextDataVac.getText();
        dataProx = TextDataProxVac.getText();

        novaVacina.setNome(nome);
        novaVacina.setCarteiraNumID(idAnimal);
        novaVacina.setDataVacina(data);
        novaVacina.setDataProximaVacina(dataProx);

        //Inserindo no banco
        resultado = Vdao.insert(novaVacina);

        if (resultado) {
            JOptionPane.showMessageDialog(null, "Sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Erro!");
        }

    }

    private void mostrarCarteira() {

        //Declaração de Objetos
        Vacina vacina = new Vacina();
        Animal animal = new Animal();

        //Declaração de Variaveis
        String nome;
        String nomeD;
        int id;

        //Atribuição de Valores
        nome = TextNomePet1.getText();
        nomeD = TextCpf1.getText();
        id = animal.Adao.IdAnimalNome(nome, nomeD);

        //Declação da Lista
        ArrayList<Vacina> listaDeVacinas = vacina.Vdao.salvarVacinaNaLista(id);

        if (posicao == listaDeVacinas.size() - 1 || posicao == -1) {
            posicao = 0;
        }

        TextNomeVacina2.setText(listaDeVacinas.get(posicao).getNome());
        TextDataVac1.setText(listaDeVacinas.get(posicao).getDataVacina());
        TextDataProxVac1.setText(listaDeVacinas.get(posicao).getDataProximaVacina());

        for (Vacina listaDeVacina : listaDeVacinas) {
            System.out.println(listaDeVacina.getNome());
            System.out.println(listaDeVacina.getDataProximaVacina());
        }
    }
}
