/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.gespet.view;

import javax.swing.JOptionPane;
import br.inatel.gespet.model.Proprietario;

/**
 *
 * @author Brendhon
 */
public class TelaEditarCliente extends javax.swing.JFrame {

    /**
     * Creates new form TelaEditarCliente
     */
    public TelaEditarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BordaLeft = new javax.swing.JPanel();
        IconVet = new javax.swing.JLabel();
        Vet = new javax.swing.JPanel();
        NomeVet = new javax.swing.JLabel();
        ButCliente = new javax.swing.JButton();
        ButAnimais = new javax.swing.JButton();
        ButVeterinario = new javax.swing.JButton();
        Bordinha = new javax.swing.JPanel();
        Bordinha1 = new javax.swing.JPanel();
        Bordinha2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BordaTop = new javax.swing.JPanel();
        IconeEditar = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        IconeCadastrar = new javax.swing.JLabel();
        TextAnimais = new javax.swing.JLabel();
        BotConferir = new javax.swing.JLabel();
        JNome2 = new javax.swing.JLabel();
        TextCpfPrp = new javax.swing.JTextField();
        Fundinho2 = new javax.swing.JLabel();
        TextCPF = new javax.swing.JTextField();
        Fundinho4 = new javax.swing.JLabel();
        JNome5 = new javax.swing.JLabel();
        TextRua = new javax.swing.JTextField();
        Fundinho5 = new javax.swing.JLabel();
        JNome4 = new javax.swing.JLabel();
        TextCelular = new javax.swing.JTextField();
        Fundinho3 = new javax.swing.JLabel();
        TextNome = new javax.swing.JTextField();
        Fundinho6 = new javax.swing.JLabel();
        JNome6 = new javax.swing.JLabel();
        JNome3 = new javax.swing.JLabel();
        TextBairro = new javax.swing.JTextField();
        Fundinho7 = new javax.swing.JLabel();
        JNome7 = new javax.swing.JLabel();
        BotEditar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TelaGeral = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BordaLeft.setBackground(new java.awt.Color(23, 105, 99));
        BordaLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconVet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconVet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Animal.png"))); // NOI18N
        BordaLeft.add(IconVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 130));

        Vet.setBackground(new java.awt.Color(1, 81, 74));

        NomeVet.setBackground(new java.awt.Color(255, 0, 153));
        NomeVet.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        NomeVet.setForeground(new java.awt.Color(255, 255, 255));
        NomeVet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomeVet.setText("NOME VET");
        NomeVet.setAlignmentX(0.5F);

        javax.swing.GroupLayout VetLayout = new javax.swing.GroupLayout(Vet);
        Vet.setLayout(VetLayout);
        VetLayout.setHorizontalGroup(
            VetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
            .addGroup(VetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(NomeVet, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
        );
        VetLayout.setVerticalGroup(
            VetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(VetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(NomeVet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
        );

        BordaLeft.add(Vet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 160, 60));

        ButCliente.setBackground(new java.awt.Color(71, 192, 161));
        ButCliente.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        ButCliente.setForeground(new java.awt.Color(255, 255, 255));
        ButCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Cliente.png"))); // NOI18N
        ButCliente.setText("CLIENTES");
        ButCliente.setBorder(null);
        ButCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButClienteActionPerformed(evt);
            }
        });
        BordaLeft.add(ButCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 150, 100));

        ButAnimais.setBackground(new java.awt.Color(71, 192, 161));
        ButAnimais.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        ButAnimais.setForeground(new java.awt.Color(255, 255, 255));
        ButAnimais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Animal.png"))); // NOI18N
        ButAnimais.setText("ANIMAIS");
        ButAnimais.setBorder(null);
        ButAnimais.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButAnimais.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButAnimais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAnimaisActionPerformed(evt);
            }
        });
        BordaLeft.add(ButAnimais, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 150, 100));

        ButVeterinario.setBackground(new java.awt.Color(71, 192, 161));
        ButVeterinario.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        ButVeterinario.setForeground(new java.awt.Color(255, 255, 255));
        ButVeterinario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Sair.png"))); // NOI18N
        ButVeterinario.setText("DESLOGAR");
        ButVeterinario.setBorder(null);
        ButVeterinario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButVeterinario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButVeterinarioActionPerformed(evt);
            }
        });
        BordaLeft.add(ButVeterinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 150, 100));

        Bordinha.setBackground(new java.awt.Color(1, 81, 74));

        javax.swing.GroupLayout BordinhaLayout = new javax.swing.GroupLayout(Bordinha);
        Bordinha.setLayout(BordinhaLayout);
        BordinhaLayout.setHorizontalGroup(
            BordinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        BordinhaLayout.setVerticalGroup(
            BordinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        BordaLeft.add(Bordinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 10, -1));

        Bordinha1.setBackground(new java.awt.Color(1, 81, 74));

        javax.swing.GroupLayout Bordinha1Layout = new javax.swing.GroupLayout(Bordinha1);
        Bordinha1.setLayout(Bordinha1Layout);
        Bordinha1Layout.setHorizontalGroup(
            Bordinha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Bordinha1Layout.setVerticalGroup(
            Bordinha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        BordaLeft.add(Bordinha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        Bordinha2.setBackground(new java.awt.Color(1, 81, 74));

        javax.swing.GroupLayout Bordinha2Layout = new javax.swing.GroupLayout(Bordinha2);
        Bordinha2.setLayout(Bordinha2Layout);
        Bordinha2Layout.setHorizontalGroup(
            Bordinha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Bordinha2Layout.setVerticalGroup(
            Bordinha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        BordaLeft.add(Bordinha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Configuracoes.png"))); // NOI18N
        BordaLeft.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 80, 80));

        getContentPane().add(BordaLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 720));

        BordaTop.setBackground(new java.awt.Color(1, 81, 74));
        BordaTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconeEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/IconEditar.png"))); // NOI18N
        IconeEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconeEditarMouseClicked(evt);
            }
        });
        BordaTop.add(IconeEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, 60));

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Home.png"))); // NOI18N
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        BordaTop.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, -1, -1, 90));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/OFF.png"))); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        BordaTop.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, -2, 60, 90));

        IconeCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/IconCadastrar.png"))); // NOI18N
        IconeCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconeCadastrarMouseClicked(evt);
            }
        });
        BordaTop.add(IconeCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 50, 60));

        getContentPane().add(BordaTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 990, 90));

        TextAnimais.setBackground(new java.awt.Color(232, 235, 244));
        TextAnimais.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        TextAnimais.setForeground(new java.awt.Color(1, 81, 74));
        TextAnimais.setText("EDITAR PROPRIETÁRIO");
        TextAnimais.setOpaque(true);
        getContentPane().add(TextAnimais, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        BotConferir.setBackground(new java.awt.Color(51, 204, 255));
        BotConferir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BotConferir.setForeground(new java.awt.Color(255, 255, 255));
        BotConferir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/BotConferir.png"))); // NOI18N
        BotConferir.setText("CONFERIR");
        BotConferir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotConferirMouseClicked(evt);
            }
        });
        getContentPane().add(BotConferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 190, 60));

        JNome2.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        JNome2.setForeground(new java.awt.Color(255, 255, 255));
        JNome2.setText("CPF DO PROPRIETÁRIO");
        getContentPane().add(JNome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 230, 20));

        TextCpfPrp.setBackground(new java.awt.Color(232, 235, 244));
        TextCpfPrp.setFont(new java.awt.Font("Typo Hoop Demo", 0, 18)); // NOI18N
        TextCpfPrp.setBorder(null);
        getContentPane().add(TextCpfPrp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 270, -1));

        Fundinho2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/FundinhoFino_1.png"))); // NOI18N
        getContentPane().add(Fundinho2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 320, 40));

        TextCPF.setEditable(false);
        TextCPF.setBackground(new java.awt.Color(232, 235, 244));
        TextCPF.setFont(new java.awt.Font("Typo Hoop Demo", 0, 18)); // NOI18N
        TextCPF.setBorder(null);
        getContentPane().add(TextCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 270, -1));

        Fundinho4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/FundinhoFino_1.png"))); // NOI18N
        getContentPane().add(Fundinho4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 320, 40));

        JNome5.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        JNome5.setForeground(new java.awt.Color(255, 255, 255));
        JNome5.setText("CPF");
        getContentPane().add(JNome5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 60, 20));

        TextRua.setEditable(false);
        TextRua.setBackground(new java.awt.Color(232, 235, 244));
        TextRua.setFont(new java.awt.Font("Typo Hoop Demo", 0, 18)); // NOI18N
        TextRua.setBorder(null);
        getContentPane().add(TextRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 450, 280, -1));

        Fundinho5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/FundinhoFino_1.png"))); // NOI18N
        getContentPane().add(Fundinho5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 320, -1));

        JNome4.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        JNome4.setForeground(new java.awt.Color(255, 255, 255));
        JNome4.setText("RUA");
        getContentPane().add(JNome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 60, 20));

        TextCelular.setEditable(false);
        TextCelular.setBackground(new java.awt.Color(232, 235, 244));
        TextCelular.setFont(new java.awt.Font("Typo Hoop Demo", 0, 18)); // NOI18N
        TextCelular.setBorder(null);
        getContentPane().add(TextCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 270, -1));

        Fundinho3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/FundinhoFino_1.png"))); // NOI18N
        getContentPane().add(Fundinho3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 320, -1));

        TextNome.setEditable(false);
        TextNome.setBackground(new java.awt.Color(232, 235, 244));
        TextNome.setFont(new java.awt.Font("Typo Hoop Demo", 0, 18)); // NOI18N
        TextNome.setBorder(null);
        getContentPane().add(TextNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 270, -1));

        Fundinho6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/FundinhoFino_1.png"))); // NOI18N
        getContentPane().add(Fundinho6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 320, 40));

        JNome6.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        JNome6.setForeground(new java.awt.Color(255, 255, 255));
        JNome6.setText("NOME");
        getContentPane().add(JNome6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 230, 20));

        JNome3.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        JNome3.setForeground(new java.awt.Color(255, 255, 255));
        JNome3.setText("CELULAR");
        getContentPane().add(JNome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 90, 20));

        TextBairro.setEditable(false);
        TextBairro.setBackground(new java.awt.Color(232, 235, 244));
        TextBairro.setFont(new java.awt.Font("Typo Hoop Demo", 0, 18)); // NOI18N
        TextBairro.setBorder(null);
        getContentPane().add(TextBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, 280, -1));

        Fundinho7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/FundinhoFino_1.png"))); // NOI18N
        getContentPane().add(Fundinho7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 320, -1));

        JNome7.setFont(new java.awt.Font("Typo Hoop Demo", 1, 18)); // NOI18N
        JNome7.setForeground(new java.awt.Color(255, 255, 255));
        JNome7.setText("BAIRRO");
        getContentPane().add(JNome7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 110, 20));

        BotEditar.setBackground(new java.awt.Color(255, 255, 255));
        BotEditar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BotEditar.setForeground(new java.awt.Color(153, 153, 153));
        BotEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/BotEditar.png"))); // NOI18N
        BotEditar.setText("EDITAR");
        BotEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotEditarMouseClicked(evt);
            }
        });
        getContentPane().add(BotEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 590, 210, 60));

        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DADOS A SEREM EDITADOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(51, 51, 51))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 326, 750, 240));

        TelaGeral.setBackground(new java.awt.Color(232, 235, 244));
        TelaGeral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Editar.png"))); // NOI18N
        TelaGeral.setOpaque(true);
        getContentPane().add(TelaGeral, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        BG.setBackground(new java.awt.Color(232, 235, 244));
        BG.setOpaque(true);
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 920, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButClienteActionPerformed

        //Declaração de Objetos
        TelaProprietario screenPrt = new TelaProprietario();

        //Mostrando tela do Proprietario
        screenPrt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButClienteActionPerformed

    private void ButAnimaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAnimaisActionPerformed

        //Declaração de Objetos
        TelaAnimais animaisScreen = new TelaAnimais();

        //Mostrar tela do Animal
        animaisScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButAnimaisActionPerformed

    private void ButVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButVeterinarioActionPerformed
        //Declaração de Objetos
        TelaLogin t = new TelaLogin();

        //Mostrar tela de vacina
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButVeterinarioActionPerformed

    private void IconeEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconeEditarMouseClicked

        //Declaração de Objetos
        TelaEditarCliente t = new TelaEditarCliente();

        //Mostrar tela editar
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IconeEditarMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked

        //Declaração de Objetos
        TelaPrincipal t = new TelaPrincipal();

        //Mostrar tela Principal
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeMouseClicked

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked

        //Fechar programa
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void IconeCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconeCadastrarMouseClicked

        //Declaração de Objetos
        TelaProprietario t = new TelaProprietario();

        //Mostrar tela de vacina
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IconeCadastrarMouseClicked

    //BotaoConferir
    private void BotConferirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotConferirMouseClicked

        conferir();

    }//GEN-LAST:event_BotConferirMouseClicked

    //BotaoEditar
    private void BotEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotEditarMouseClicked

        editar();

    }//GEN-LAST:event_BotEditarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEditarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JPanel BordaLeft;
    private javax.swing.JPanel BordaTop;
    private javax.swing.JPanel Bordinha;
    private javax.swing.JPanel Bordinha1;
    private javax.swing.JPanel Bordinha2;
    private javax.swing.JLabel BotConferir;
    private javax.swing.JLabel BotEditar;
    private javax.swing.JButton ButAnimais;
    private javax.swing.JButton ButCliente;
    private javax.swing.JButton ButVeterinario;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel Fundinho2;
    private javax.swing.JLabel Fundinho3;
    private javax.swing.JLabel Fundinho4;
    private javax.swing.JLabel Fundinho5;
    private javax.swing.JLabel Fundinho6;
    private javax.swing.JLabel Fundinho7;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel IconVet;
    private javax.swing.JLabel IconeCadastrar;
    private javax.swing.JLabel IconeEditar;
    private javax.swing.JLabel JNome2;
    private javax.swing.JLabel JNome3;
    private javax.swing.JLabel JNome4;
    private javax.swing.JLabel JNome5;
    private javax.swing.JLabel JNome6;
    private javax.swing.JLabel JNome7;
    private javax.swing.JLabel NomeVet;
    private javax.swing.JLabel TelaGeral;
    private javax.swing.JLabel TextAnimais;
    private javax.swing.JTextField TextBairro;
    private javax.swing.JTextField TextCPF;
    private javax.swing.JTextField TextCelular;
    private javax.swing.JTextField TextCpfPrp;
    private javax.swing.JTextField TextNome;
    private javax.swing.JTextField TextRua;
    private javax.swing.JPanel Vet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private void editar() {

        //Declaração de Objetos
        Proprietario proprietario = new Proprietario();

        //Declaração de Variaveis
        String cpfAtual;
        int cpfAux;

        cpfAtual = TextCpfPrp.getText();

        if (cpfAtual.length() == 11) {

            try {

                //Atualizando dados
                proprietario.Pdao.atualizarProprietarioBairroPeloCpf(TextBairro.getText(), cpfAtual);
                proprietario.Pdao.atualizarProprietarioRuaPeloCpf(TextRua.getText(), cpfAtual);
                proprietario.Pdao.atualizarProprietarioCelularPeloCpf(Integer.parseInt(TextCelular.getText()), cpfAtual);
                proprietario.Pdao.atualizarProprietarioNomePeloCpf(TextNome.getText(), cpfAtual);

                //Deixando as caixas te textos vazias
                TextBairro.setText(null);
                TextCpfPrp.setText(null);
                TextCPF.setText(null);
                TextCelular.setText(null);
                TextNome.setText(null);
                TextRua.setText(null);

                //Para deixar editavel
                TextNome.setEditable(false);
                TextCPF.setEditable(false);
                TextCelular.setEditable(false);
                TextRua.setEditable(false);
                TextBairro.setEditable(false);

                //Saida
                JOptionPane.showMessageDialog(null, "Sucesso ao Editar!");

            } catch (NumberFormatException ex) {

                JOptionPane.showMessageDialog(null, "APENAS NUMEROS NO CELULAR");

            }
        }
    }

    private void conferir() {

        //Declaração de Objetos
        Proprietario proprietario = new Proprietario();

        //Declaração de variaveis
        int aux;
        String cpf;

        //Atribuição de Valores
        aux = 0;
        cpf = TextCpfPrp.getText();
        
        if (TextCpfPrp.getText().length() == 11) {
            try {

                for (Proprietario proprietario1 : proprietario.Pdao.buscarUsuariosSemFiltro()) {
                    if (proprietario1.getCpf().contentEquals(cpf)) {

                        //Pegando os valores correspondentes ao cpf 
                        TextNome.setText(proprietario1.getNome());
                        TextCPF.setText(proprietario1.getCpf());
                        TextCpfPrp.setText(proprietario1.getCpf());
                        TextCelular.setText(Integer.toString(proprietario1.getCelular()));
                        TextRua.setText(proprietario1.getRua());
                        TextBairro.setText(proprietario1.getBairro());

                        //Para deixar editavel
                        TextNome.setEditable(true);
                        TextCPF.setEditable(true);
                        TextCelular.setEditable(true);
                        TextRua.setEditable(true);
                        TextBairro.setEditable(true);

                        aux++;
                        break;
                    } else {
                        TextCpfPrp.setText(null);
                    }
                }
            } catch (NumberFormatException ex) {
                //Para deixar ineditavel
                TextNome.setEditable(false);
                TextCPF.setEditable(false);
                TextCelular.setEditable(false);
                TextRua.setEditable(false);
                TextBairro.setEditable(false);

                //Para limpar as colunas
                TextNome.setText(null);
                TextCPF.setText(null);
                TextCelular.setText(null);
                TextRua.setText(null);
                TextBairro.setText(null);
                JOptionPane.showMessageDialog(null, "ENTRE COM APENAS NUMEROS PARA CELULAR E CPF!");
            }
        } else {
            //Para deixar ineditavel
            TextNome.setEditable(false);
            TextCPF.setEditable(false);
            TextCelular.setEditable(false);
            TextRua.setEditable(false);
            TextBairro.setEditable(false);

            //Para limpar as colunas
            TextNome.setText(null);
            TextCPF.setText(null);
            TextCelular.setText(null);
            TextRua.setText(null);
            TextBairro.setText(null);
            JOptionPane.showMessageDialog(null, "ENTRE COM 11 NUMEROS EM CPF");
        }
        if (aux == 0) {
            //Para deixar ineditavel
            TextNome.setEditable(false);
            TextCPF.setEditable(false);
            TextCelular.setEditable(false);
            TextRua.setEditable(false);
            TextBairro.setEditable(false);

            //Para limpar as colunas
            TextNome.setText(null);
            TextCPF.setText(null);
            TextCelular.setText(null);
            TextRua.setText(null);
            TextBairro.setText(null);
            JOptionPane.showMessageDialog(null, "CPF NÃO ENCONTRADO");
        }

    }
}
